// Auto Wala — whatever is loudest. Remix era, item numbers, party anthems and
// the Punjabi-pop that every auto subwoofer was built for.

export default [
  { t: 'Dilbar Dilbar', f: 'Sirf Tum', y: 1999 },
  { t: 'Kaanta Laga', a: 'DJ Doll', y: 2002 },
  { t: 'Tunak Tunak Tun', a: 'Daler Mehndi', y: 1998 },
  { t: 'Bolo Ta Ra Ra', a: 'Daler Mehndi', y: 1995 },
  { t: 'Aankh Marey', f: 'Simmba', y: 2018 },
  { t: 'Munni Badnaam Hui', f: 'Dabangg', y: 2010 },
  { t: 'Sheila Ki Jawani', f: 'Tees Maar Khan', y: 2010 },
  { t: 'Chikni Chameli', f: 'Agneepath', y: 2012 },
  { t: 'Lungi Dance', f: 'Chennai Express', y: 2013 },
  { t: 'Abhi Toh Party Shuru Hui Hai', f: 'Khoobsurat', y: 2014 },
  { t: 'Tamma Tamma Loge', f: 'Thanedaar', y: 1990 },
  { t: 'Saturday Saturday', f: 'Humpty Sharma Ki Dulhania', y: 2014 },

  { t: 'Ho Jayegi Balle Balle', a: 'Daler Mehndi', y: 1997 },
  { t: 'Na Na Na Na Re', a: 'Daler Mehndi', y: 1996 },
  { t: 'Dardi Rab Rab', a: 'Daler Mehndi', y: 1998 },
  { t: 'Kaliyon Ka Chaman', a: 'Meet Bros', y: 2003, q: 'Kaliyon Ka Chaman remix Meet Bros Anjjan 2003' },
  { t: 'Kaanta Laga Remix', a: 'DJ Doll', y: 2002, q: 'Kaanta Laga DJ Doll remix official video' },
  { t: 'Kaliyon Ka Chaman Jab', f: 'Jyoti', y: 1981 },
  { t: 'Babuji Zara Dheere Chalo', f: 'Dum', y: 2003 },
  { t: 'Aa Ante Amalapuram', f: 'Maximum', y: 2012 },
  { t: 'Beedi Jalaile', f: 'Omkara', y: 2006 },
  { t: 'Namak Ishq Ka', f: 'Omkara', y: 2006 },
  { t: 'Kajra Re Kajra Re', f: 'Bunty Aur Babli', y: 2005 },
  { t: 'Dhan Te Nan', f: 'Kaminey', y: 2009 },
  { t: 'Emosanal Attyachar', f: 'Dev.D', y: 2009 },
  { t: 'Zor Ka Jhatka', f: 'Action Replayy', y: 2010 },
  { t: 'Desi Boyz', f: 'Desi Boyz', y: 2011 },
  { t: 'Subha Hone Na De', f: 'Desi Boyz', y: 2011 },
  { t: 'Party On My Mind', f: 'Race 2', y: 2013 },
  { t: 'Lat Lag Gayee', f: 'Race 2', y: 2013 },
  { t: 'Balam Pichkari', f: 'Yeh Jawaani Hai Deewani', y: 2013 },
  { t: 'Badtameez Dil', f: 'Yeh Jawaani Hai Deewani', y: 2013 },
  { t: 'Dilliwaali Girlfriend', f: 'Yeh Jawaani Hai Deewani', y: 2013 },
  { t: 'Gandi Baat', f: 'R... Rajkumar', y: 2013 },
  { t: 'Saree Ke Fall Sa', f: 'R... Rajkumar', y: 2013 },
  { t: 'Tune Maari Entriyaan', f: 'Gunday', y: 2014 },
  { t: 'Baby Doll', f: 'Ragini MMS 2', y: 2014 },
  { t: 'Chittiyaan Kalaiyaan', f: 'Roy', y: 2015 },
  { t: 'Kar Gayi Chull', f: 'Kapoor & Sons', y: 2016 },
  { t: 'The Humma Song', f: 'OK Jaanu', y: 2017 },
  { t: 'Kamariya', f: 'Stree', y: 2018 },
  { t: 'Coca Cola', f: 'Luka Chuppi', y: 2019 },
  { t: 'Garmi', f: 'Street Dancer 3D', y: 2020 },
  { t: 'Nashe Si Chadh Gayi', f: 'Befikre', y: 2016 },
  { t: 'Ude Dil Befikre', f: 'Befikre', y: 2016 },
  { t: 'Cutiepie', f: 'Ae Dil Hai Mushkil', y: 2016 },
  { t: 'The Breakup Song', f: 'Ae Dil Hai Mushkil', y: 2016 },
  { t: 'Kala Chashma Baar Baar', f: 'Baar Baar Dekho', y: 2016, q: 'Kala Chashma full video Baar Baar Dekho Sidharth Katrina' },
  { t: 'Tamma Tamma Again', f: 'Badrinath Ki Dulhania', y: 2017 },
  { t: 'Badri Ki Dulhania', f: 'Badrinath Ki Dulhania', y: 2017 },
  { t: 'Dilbar', f: 'Satyameva Jayate', y: 2018 },
  { t: 'Ghungroo', f: 'War', y: 2019 },
  { t: 'Naach Meri Rani', a: 'Guru Randhawa', y: 2020 },
  { t: 'Slowly Slowly', a: 'Guru Randhawa', y: 2019 },
  { t: 'Lahore', a: 'Guru Randhawa', y: 2017 },
  { t: 'Suit Suit', f: 'Hindi Medium', y: 2017 },
  { t: 'Ban Ja Rani', f: 'Tumhari Sulu', y: 2017 },
  { t: 'Morni Banke', f: 'Badhaai Ho', y: 2018 },
  { t: 'Nachde Ne Saare', f: 'Baar Baar Dekho', y: 2016 },
  { t: 'Proper Patola', f: 'Namaste England', y: 2018 },
  { t: 'Swag Se Swagat', f: 'Tiger Zinda Hai', y: 2017 },
  { t: 'Jumme Ki Raat', f: 'Kick', y: 2014 },
  { t: 'Hangover', f: 'Kick', y: 2014 },
  { t: 'Selfie Le Le Re', f: 'Bajrangi Bhaijaan', y: 2015 },
  { t: 'Chicken Song', f: 'Bajrangi Bhaijaan', y: 2015 },
  { t: 'Fevicol Se', f: 'Dabangg 2', y: 2012 },
  { t: 'Pandey Jee Seeti', f: 'Dabangg 2', y: 2012 },
  { t: 'Aa Re Pritam Pyare', f: 'Rowdy Rathore', y: 2012 },
  { t: 'Chinta Ta Chita Chita', f: 'Rowdy Rathore', y: 2012 },
  { t: 'Anarkali Disco Chali', f: 'Housefull 2', y: 2012 },
  { t: 'Right Now Now', f: 'Housefull 2', y: 2012 },
  { t: 'Party All Night', f: 'Boss', y: 2013 },
  { t: 'Blue Eyes', a: 'Yo Yo Honey Singh', y: 2013 },
  { t: 'Brown Rang', a: 'Yo Yo Honey Singh', y: 2011 },
  { t: 'Angreji Beat', a: 'Yo Yo Honey Singh', y: 2012 },
  { t: 'Char Bottle Vodka', f: 'Ragini MMS 2', y: 2014 },
  { t: 'Sunny Sunny', f: 'Yaariyan', y: 2014 },
  { t: 'Nasha', f: 'Yaariyan', y: 2014 },
  { t: 'Manali Trance', f: 'The Shaukeens', y: 2014 },
  { t: 'Dheere Dheere Se Meri Zindagi', a: 'Yo Yo Honey Singh', y: 2015 },
  { t: 'Wakhra Swag', f: 'Judgementall Hai Kya', y: 2019 },
  { t: 'Illegal Weapon 2.0', f: 'Street Dancer 3D', y: 2020 },
  { t: 'Muqabla', f: 'Street Dancer 3D', y: 2020 },
  { t: 'Urvashi', a: 'Yo Yo Honey Singh', y: 2018 },
  { t: 'Makhna', a: 'Yo Yo Honey Singh', y: 2019 },
  { t: 'Aashiq Banaya Aapne', f: 'Aashiq Banaya Aapne', y: 2005 },
  { t: 'Crazy Kiya Re', f: 'Dhoom 2', y: 2006 },
  { t: 'Dhoom Again', f: 'Dhoom 2', y: 2006 },
  { t: 'Dhoom Machale', f: 'Dhoom', y: 2004 },
  { t: 'Deewangi Deewangi', f: 'Om Shanti Om', y: 2007 },
  { t: 'Dard-E-Disco', f: 'Om Shanti Om', y: 2007 },
  { t: 'Aaj Ki Raat', f: 'Don', y: 2006 },
  { t: 'Mauja Hi Mauja', f: 'Jab We Met', y: 2007 },
  { t: 'Nagada Nagada', f: 'Jab We Met', y: 2007 },
  { t: 'Pungi', f: 'Agent Vinod', y: 2012 },
  { t: 'Jalebi Bai', f: 'Double Dhamaal', y: 2011 },
  { t: 'Character Dheela', f: 'Ready', y: 2011 },
  { t: 'Dhinka Chika', f: 'Ready', y: 2011 },
];
