// Barish Wala — monsoon. Sawan songs, rain picturisations, and everything that
// sounds like the first drops on a tin awning.

export default [
  { t: 'Rimjhim Gire Sawan', f: 'Manzil', y: 1979 },
  { t: 'Bheegi Bheegi Raaton Mein', f: 'Ajnabee', y: 1974, q: 'Bheegi Bheegi Raaton Mein Ajnabee Kishore Kumar Lata Mangeshkar 1974' },
  { t: 'Ab Ke Sawan', a: 'Shubha Mudgal', y: 1999 },
  { t: 'Barso Re', f: 'Guru', y: 2007 },
  { t: 'Tip Tip Barsa Paani', f: 'Mohra', y: 1994 },
  { t: 'Kaate Nahi Kat Te', f: 'Mr. India', y: 1987 },
  { t: 'Ghanan Ghanan', f: 'Lagaan', y: 2001 },
  { t: 'Koi Ladki Hai', f: 'Dil To Pagal Hai', y: 1997 },
  { t: 'Bheegi Bheegi', f: 'Gangster', y: 2006, q: 'Bheegi Bheegi Gangster James Atif Aslam full song Emraan Kangana' },
  { t: 'Zara Zara', f: 'Rehnaa Hai Terre Dil Mein', y: 2001 },
  { t: 'Megha Re Megha', f: 'Pyaasa Sawan', y: 1981 },
  { t: 'Lagi Aaj Sawan Ki', f: 'Chandni', y: 1989 },

  { t: 'Sawan Ka Mahina', f: 'Milan', y: 1967 },
  { t: 'Ek Ladki Bheegi Bhagi Si Barish', f: 'Chalti Ka Naam Gaadi', y: 1958, q: 'Ek Ladki Bheegi Bhagi Si Kishore Kumar Chalti Ka Naam Gaadi' },
  { t: 'Pyar Hua Ikrar Hua Barish', f: 'Shree 420', y: 1955, q: 'Pyar Hua Ikrar Hua Shree 420 Manna Dey Lata rain song' },
  { t: 'Bheegi Bheegi Raaton Mein Barish', f: 'Ajnabee', y: 1974, q: 'Bheegi Bheegi Raaton Mein Ajnabee Rajesh Khanna Zeenat' },
  { t: 'Dekho Na', f: 'Fanaa', y: 2006 },
  { t: 'Chand Sifarish', f: 'Fanaa', y: 2006 },
  { t: 'Mere Haath Mein', f: 'Fanaa', y: 2006 },
  { t: 'Chanda Chamke', f: 'Fanaa', y: 2006 },
  { t: 'Sawan Aaya Hai', f: 'Creature 3D', y: 2014 },
  { t: 'Kaise Mujhe Barish', f: 'Ghajini', y: 2008, q: 'Kaise Mujhe Tum Mil Gayi Ghajini full song' },
  { t: 'Barsaat Ke Din Aaye', f: 'Barsaat', y: 2005 },
  { t: 'Barsaat Ke Mausam Mein', f: 'Naajayaz', y: 1995 },
  { t: 'Aaj Rapat Jaaye Barish', f: 'Namak Halaal', y: 1982, q: 'Aaj Rapat Jaaye To Namak Halaal rain song Kishore Asha' },
  { t: 'Rimjhim Rimjhim', f: '1942: A Love Story', y: 1994, q: 'Rimjhim Rimjhim 1942 A Love Story Kumar Sanu Kavita' },
  { t: 'Ek Ladki Ko Dekha Barish', f: '1942: A Love Story', y: 1994, q: 'Ek Ladki Ko Dekha Toh Aisa Laga 1942 A Love Story Kumar Sanu' },
  { t: 'Bheegi Bheegi Raton Mein Nazrein', f: 'Ajnabee', y: 1974, q: 'Bheegi Bheegi Raton Mein Kishore Kumar Lata duet' },
  { t: 'Hai Rama Barish', f: 'Rangeela', y: 1995, q: 'Hai Rama Rangeela Hariharan Swarnalatha full song' },
  { t: 'Sawan Barse Tarse Dil', f: 'Dahek', y: 1999 },
  { t: 'Barsaat Ho Rahi Hai', a: 'Falguni Pathak', q: 'Barsaat Ke Din Aaye Falguni Pathak song' },
  { t: 'Yaad Piya Ki Aane Lagi', a: 'Falguni Pathak', y: 1999 },
  { t: 'Maine Payal Hai Chhankai', a: 'Falguni Pathak', y: 1999 },
  { t: 'Meri Chunar Udd Udd Jaye', a: 'Falguni Pathak', y: 2000 },
  { t: 'Bheega Bheega Sa Ye Mausam', a: 'Falguni Pathak', q: 'Falguni Pathak rain monsoon song' },
  { t: 'Sawan Mein Lag Gayi Aag', f: 'Ginny Weds Sunny', y: 2020 },
  { t: 'Mausam Ki Tarah', f: 'Fitoor', y: 2016, q: 'Pashmina Fitoor Amit Trivedi full song' },
  { t: 'Paani Da Rang', f: 'Vicky Donor', y: 2012 },
  { t: 'Rum Whisky', f: 'Vicky Donor', y: 2012, q: 'Rum Whiskey Vicky Donor song' },
  { t: 'Ambarsariya', f: 'Fukrey', y: 2013 },
  { t: 'Bholi Si Surat', f: 'Dil To Pagal Hai', y: 1997 },
  { t: 'Dil To Pagal Hai', f: 'Dil To Pagal Hai', y: 1997 },
  { t: 'Are Re Are', f: 'Dil To Pagal Hai', y: 1997 },
  { t: 'Le Gayi Le Gayi', f: 'Dil To Pagal Hai', y: 1997 },
  { t: 'Ghar Se Nikalte Hi Barish', f: 'Papa Kehte Hain', y: 1996, q: 'Ghar Se Nikalte Hi Papa Kehte Hain Udit Narayan' },
  { t: 'Tum Se Milne Ko Dil', f: 'Phool Aur Kaante', y: 1991 },
  { t: 'Saawan Ke Jhoole Pade', f: 'Jurmana', y: 1979 },
  { t: 'Ghir Ghir Ke Aayi Badariya', f: 'Anokhi Ada', y: 1973, q: 'Ghir Ghir Ke Aayi Badariya monsoon hindi song' },
  { t: 'Kali Ghata Chhaye', f: 'Sujata', y: 1959, q: 'Kaali Ghata Chhaye Mora Jiya Tarsaye song' },
  { t: 'O Sajna Barkha Bahar Aayi', f: 'Parakh', y: 1960 },
  { t: 'Zindagi Bhar Nahi Bhoolegi Barish', f: 'Barsaat Ki Raat', y: 1960, q: 'Zindagi Bhar Nahi Bhoolegi Barsaat Ki Raat Mohammed Rafi' },
  { t: 'Garjat Barsat Sawan', f: 'Barsaat Ki Raat', y: 1960, q: 'Garjat Barsat Sawan Aayo Barsaat Ki Raat song' },
  { t: 'Bheegi Hui Hai Raat Magar', f: 'Chandi Sona', y: 1977 },
  { t: 'Kabhi Kabhi Aditi Barish', f: 'Jaane Tu Ya Jaane Na', y: 2008, q: 'Kabhi Kabhi Aditi Rashid Ali Jaane Tu Ya Jaane Na' },
  { t: 'Pehli Baarish', a: 'Jubin Nautiyal', q: 'Pehli Baarish Jubin Nautiyal song' },
  { t: 'Barish', a: 'Atif Aslam', q: 'Barish Half Girlfriend Ash King Shashaa Tirupati' },
  { t: 'Barish Half Girlfriend', f: 'Half Girlfriend', y: 2017, q: 'Baarish Half Girlfriend Ash King full song' },
  { t: 'Phir Bhi Tumko Chaahunga', f: 'Half Girlfriend', y: 2017 },
  { t: 'Main Phir Bhi Tumko', f: 'Half Girlfriend', y: 2017, q: 'Main Phir Bhi Tumko Chahunga Arijit Singh full song' },
  { t: 'Thodi Der', f: 'Half Girlfriend', y: 2017 },
  { t: 'Sawan Aaya', a: 'Arijit Singh', q: 'Sawan Aaya Hai Creature 3D Arijit Singh full song' },
  { t: 'Ek Baarish', a: 'Shreya Ghoshal', q: 'Baarish Yaariyan Mohammed Irfan song' },
  { t: 'Baarish Yaariyan', f: 'Yaariyan', y: 2014 },
  { t: 'Bheegi Si Bhaagi Si', f: 'Raajneeti', y: 2010 },
  { t: 'Mora Piya', f: 'Raajneeti', y: 2010 },
  { t: 'Chala Kahin Door', f: 'Raajneeti', y: 2010, q: 'Ishwar Allah Raajneeti song' },
  { t: 'Tere Bina Barish', f: 'Wazir', y: 2016, q: 'Tere Bina Wazir Sonu Nigam Shreya Ghoshal full song' },
  { t: 'Barsaat Ki Dhun', a: 'Jubin Nautiyal', y: 2021 },
  { t: 'Tum Hi Aana', f: 'Marjaavaan', y: 2019 },
  { t: 'Bekhayali', f: 'Kabir Singh', y: 2019 },
  { t: 'Kaise Hua', f: 'Kabir Singh', y: 2019 },
  { t: 'Pehla Pyaar', f: 'Kabir Singh', y: 2019 },
  { t: 'Mehrama', f: 'Love Aaj Kal', y: 2020 },
  { t: 'Ve Maahi Barish', f: 'Kesari', y: 2019, q: 'Ve Maahi Kesari Arijit Singh Asees Kaur full song' },
  { t: 'Saawan Mein Lag Gayi Aag Mika', a: 'Mika Singh', q: 'Sawan Mein Lag Gayi Aag Neha Kakkar Badshah song' },
  { t: 'Rimjhim Gire Sawan Lata', f: 'Manzil', y: 1979, q: 'Rimjhim Gire Sawan Lata Mangeshkar Manzil female version' },
  { t: 'Ek Ajnabee Haseena Barish', f: 'Ajnabee', y: 1974, q: 'Ek Ajnabee Haseena Se Kishore Kumar Ajnabee song' },
  { t: 'Tum Aa Gaye Ho Barish', f: 'Aandhi', y: 1975, q: 'Tum Aa Gaye Ho Noor Aa Gaya Aandhi Kishore Lata' },
  { t: 'Sili Hawa Chhoo Gayi', f: 'Libaas', y: 1988 },
  { t: 'Bheegi Palkein', f: 'Anokha Rishta', y: 1986, q: 'Bheegi palkon par hindi sad song' },
  { t: 'Kuch Na Kaho Barish', f: '1942: A Love Story', y: 1994, q: 'Kuch Na Kaho 1942 A Love Story Kumar Sanu full song' },
  { t: 'Yeh Safar', f: '1942: A Love Story', y: 1994 },
  { t: 'Pyar Hua Chupke Se', f: '1942: A Love Story', y: 1994 },
  { t: 'Mausam Hai Aashiqana Barish', f: 'Pakeezah', y: 1972, q: 'Mausam Hai Aashiqana Pakeezah Lata Mangeshkar' },
  { t: 'Nain Ladh Jaihen', f: 'Gunga Jumna', y: 1961 },
  { t: 'Sawan Ke Mahine Mein', f: 'Sharaabi', y: 1984 },
  { t: 'Barkha Rani', f: 'Sabse Bada Rupaiya', y: 1976, q: 'Barkha Rani Zara Jam Ke Barso monsoon song' },
  { t: 'Aaj Blue Hai Paani', f: 'Yaariyan', y: 2014 },
  { t: 'Kabhi Jo Baadal Barse Barish', f: 'Jackpot', y: 2013, q: 'Kabhi Jo Baadal Barse Arijit Singh Jackpot full song' },
  { t: 'Tum Jo Aaye Barish', f: 'Once Upon A Time In Mumbaai', y: 2010, q: 'Tum Jo Aaye Zindagi Mein Rahat Fateh Ali Khan full song' },
  { t: 'Aayat', f: 'Bajirao Mastani', y: 2015 },
  { t: 'Albela Sajan Barish', f: 'Bajirao Mastani', y: 2015, q: 'Albela Sajan Aayo Re Bajirao Mastani full song' },
  { t: 'Moh Moh Ke Dhaage', f: 'Dum Laga Ke Haisha', y: 2015 },
  { t: 'Dard Karaara', f: 'Dum Laga Ke Haisha', y: 2015 },
  { t: 'Agar Tum Saath Ho Barish', f: 'Tamasha', y: 2015, q: 'Agar Tum Saath Ho Tamasha Alka Yagnik Arijit full song' },
  { t: 'Sooraj Dooba Hai Barish', f: 'Roy', y: 2015, q: 'Sooraj Dooba Hain Roy Arijit Singh full video song' },
  { t: 'Chahun Main Ya Naa Barish', f: 'Aashiqui 2', y: 2013, q: 'Chahun Main Ya Naa Aashiqui 2 Palak Muchhal full song' },
  { t: 'Sun Raha Hai Na Tu Barish', f: 'Aashiqui 2', y: 2013, q: 'Sun Raha Hai Na Tu Ankit Tiwari Aashiqui 2 full song' },
  { t: 'Meherbaan Barish', f: 'Bang Bang', y: 2014, q: 'Meherbaan Bang Bang Shafqat Amanat Ali full song' },
];
