// Bus Wala — daytime travel. Window seat, hills on one side, the road going
// somewhere. Upbeat and open-air rather than melancholy.

export default [
  { t: 'Zindagi Ek Safar Hai Suhana', f: 'Andaz', y: 1971 },
  { t: 'Musafir Hoon Yaaron', f: 'Parichay', y: 1972 },
  { t: 'Suhana Safar Aur Yeh Mausam Haseen', f: 'Madhumati', y: 1958 },
  { t: 'Yeh Dosti Hum Nahi Todenge', f: 'Sholay', y: 1975 },
  { t: 'Panchhi Banoon Udti Phiroon', f: 'Chori Chori', y: 1956 },
  { t: 'Safarnama', f: 'Tamasha', y: 2015 },
  { t: 'Yun Hi Chala Chal', f: 'Swades', y: 2004 },
  { t: 'Aane Wala Pal', f: 'Golmaal', y: 1979 },
  { t: 'Ruk Jana Nahin', f: 'Imtihan', y: 1974 },
  { t: 'Mera Joota Hai Japani', f: 'Shree 420', y: 1955 },
  { t: 'Chala Jaata Hoon', f: 'Mere Jeevan Saathi', y: 1972 },
  { t: 'Dil Chahta Hai', f: 'Dil Chahta Hai', y: 2001 },

  { t: 'Yeh Jo Des Hai Tera', f: 'Swades', y: 2004 },
  { t: 'Yeh Tara Woh Tara', f: 'Swades', y: 2004 },
  { t: 'Koi Kahe Kehta Rahe', f: 'Dil Chahta Hai', y: 2001 },
  { t: 'Jaane Kyun Dil Jaanta Hai', f: 'Dil Chahta Hai', y: 2001 },
  { t: 'Kabhi Kabhi Aditi', f: 'Jaane Tu... Ya Jaane Na', y: 2008 },
  { t: 'Pappu Cant Dance', f: 'Jaane Tu... Ya Jaane Na', y: 2008 },
  { t: 'Kabhi Kabhi Aditi Zindagi', f: 'Jaane Tu... Ya Jaane Na', y: 2008, q: 'Kabhi Kabhi Aditi Zindagi Mein Yun Hi Jaane Tu Ya Jaane Na full song' },
  { t: 'Senorita', f: 'Zindagi Na Milegi Dobara', y: 2011 },
  { t: 'Der Lagi Lekin', f: 'Zindagi Na Milegi Dobara', y: 2011 },
  { t: 'Khaabon Ke Parinday', f: 'Zindagi Na Milegi Dobara', y: 2011 },
  { t: 'Sooraj Ki Baahon Mein', f: 'Zindagi Na Milegi Dobara', y: 2011 },
  { t: 'Dil Dhadakne Do', f: 'Zindagi Na Milegi Dobara', y: 2011 },
  { t: 'Give Me Some Sunshine', f: '3 Idiots', y: 2009 },
  { t: 'All Izz Well', f: '3 Idiots', y: 2009 },
  { t: 'Zoobi Doobi', f: '3 Idiots', y: 2009 },
  { t: 'Masti Ki Paathshaala', f: 'Rang De Basanti', y: 2006 },
  { t: 'Rang De Basanti', f: 'Rang De Basanti', y: 2006 },
  { t: 'Khalbali', f: 'Rang De Basanti', y: 2006 },
  { t: 'Roobaroo', f: 'Rang De Basanti', y: 2006 },
  { t: 'Yaadein Yaad Aati Hain', f: 'Love Story', y: 1981 },
  { t: 'Ye Jo Des Hai', f: 'Swades', y: 2004, q: 'Yeh Jo Des Hai Tera Swades A R Rahman full song' },
  { t: 'Bum Bum Bole', f: 'Taare Zameen Par', y: 2007 },
  { t: 'Aaoge Jab Tum', f: 'Jab We Met', y: 2007 },
  { t: 'Tum Se Hi', f: 'Jab We Met', y: 2007 },
  { t: 'Yeh Ishq Hai', f: 'Jab We Met', y: 2007 },
  { t: 'Chori Kiya Re Jiya', f: 'Dabangg', y: 2010 },
  { t: 'Panchhi Nadiya Pawan Ke Jhonke', f: 'Refugee', y: 2000 },
  { t: 'Aisa Lagta Hai', f: 'Refugee', y: 2000 },
  { t: 'Chalo Chale Mitwa', f: 'Dil Se..', y: 1998 },
  { t: 'Dil Se Re', f: 'Dil Se..', y: 1998 },
  { t: 'Jiya Jale', f: 'Dil Se..', y: 1998 },
  { t: 'Satrangi Re', f: 'Dil Se..', y: 1998 },
  { t: 'Rangeela Re', f: 'Rangeela', y: 1995 },
  { t: 'Hai Rama', f: 'Rangeela', y: 1995 },
  { t: 'Tanha Tanha', f: 'Rangeela', y: 1995 },
  { t: 'Yaaron Sun Lo Zara', f: 'Rockford', y: 1999 },
  { t: 'Yaaron Dosti', a: 'KK', y: 1999 },
  { t: 'Pal', a: 'KK', y: 1999 },
  { t: 'Aap Ki Yaad Aati Rahi', f: 'Gharaonda', y: 1977 },
  { t: 'Panchi Banoon', f: 'Chori Chori', y: 1956, q: 'Panchi Banoon Udti Phiroon Chori Chori Lata Mangeshkar original' },
  { t: 'Ude Jab Jab Zulfein Teri', f: 'Naya Daur', y: 1957 },
  { t: 'Yeh Desh Hai Veer Jawano Ka', f: 'Naya Daur', y: 1957 },
  { t: 'Maang Ke Saath Tumhara', f: 'Naya Daur', y: 1957 },
  { t: 'Saathi Haath Badhana', f: 'Naya Daur', y: 1957 },
  { t: 'Aaja Sanam Madhur Chandni Mein', f: 'Chori Chori', y: 1956 },
  { t: 'Yeh Raat Bheegi Bheegi', f: 'Chori Chori', y: 1956 },
  { t: 'Ramaiya Vastavaiya', f: 'Shree 420', y: 1955 },
  { t: 'Pyar Hua Ikrar Hua', f: 'Shree 420', y: 1955 },
  { t: 'Ichak Dana Beechak Dana', f: 'Shree 420', y: 1955 },
  { t: 'Awara Hoon', f: 'Awaara', y: 1951 },
  { t: 'Dum Dum Diga Diga', f: 'Chhalia', y: 1960 },
  { t: 'Chhalia Mera Naam', f: 'Chhalia', y: 1960 },
  { t: 'Sar Jo Tera Chakraye', f: 'Pyaasa', y: 1957 },
  { t: 'Babuji Dheere Chalna', f: 'Aar Paar', y: 1954 },
  { t: 'Sun Sun Sun Zalima', f: 'Aar Paar', y: 1954 },
  { t: 'Aana Meri Jaan Sunday Ke Sunday', f: 'Shehnai', y: 1947 },
  { t: 'Hum Honge Kamyab', a: 'Girija Devi', q: 'Hum Honge Kamyab Ek Din song' },
  { t: 'Nanha Munna Rahi Hoon', f: 'Son Of India', y: 1962 },
  { t: 'Chalti Ka Naam Gaadi', f: 'Chalti Ka Naam Gaadi', y: 1958, q: 'Babu Samjho Ishaare Chalti Ka Naam Gaadi Kishore Kumar' },
  { t: 'Ek Ladki Bheegi Bhaagi Si', f: 'Chalti Ka Naam Gaadi', y: 1958 },
  { t: 'Paanch Rupaiya Baara Anna', f: 'Chalti Ka Naam Gaadi', y: 1958 },
  { t: 'Haal Kaisa Hai Janaab Ka', f: 'Chalti Ka Naam Gaadi', y: 1958 },
  { t: 'Chhoo Kar Mere Man Ko', f: 'Yaarana', y: 1981 },
  { t: 'Sara Zamana Haseeno Ka Deewana', f: 'Yaarana', y: 1981 },
  { t: 'Papa Kehte Hain Bada Naam', f: 'Qayamat Se Qayamat Tak', y: 1988, q: 'Papa Kehte Hain Bada Naam Karega QSQT Udit Narayan' },
  { t: 'Ilu Ilu', f: 'Saudagar', y: 1991 },
  { t: 'Imli Ka Boota', f: 'Saudagar', y: 1991 },
  { t: 'Bade Achhe Lagte Hain', f: 'Balika Badhu', y: 1976 },
  { t: 'Gaadi Wala Aaya', a: 'Folk', q: 'Chalte Chalte Kishore Kumar road song' },
  { t: 'Sun Raha Hai Na Tu', f: 'Aashiqui 2', y: 2013 },
  { t: 'Manwa Laage', f: 'Happy New Year', y: 2014 },
  { t: 'Patakha Guddi', f: 'Highway', y: 2014 },
  { t: 'Sooha Saha', f: 'Highway', y: 2014 },
  { t: 'Maahi Ve', f: 'Highway', y: 2014 },
  { t: 'Wanna Mash Up', f: 'Highway', y: 2014, q: 'Kahaan Hoon Main Highway Jonita Gandhi A R Rahman' },
  { t: 'Phir Se Ud Chala', f: 'Rockstar', y: 2011 },
  { t: 'Sadda Haq', f: 'Rockstar', y: 2011 },
  { t: 'Jo Bhi Main', f: 'Rockstar', y: 2011 },
  { t: 'Matargashti', f: 'Tamasha', y: 2015 },
  { t: 'Heer Toh Badi Sad Hai', f: 'Tamasha', y: 2015 },
  { t: 'Chali Kahani', f: 'Tamasha', y: 2015 },
  { t: 'Ilahi Reprise', f: 'Yeh Jawaani Hai Deewani', y: 2013, q: 'Ilahi Reprise Yeh Jawaani Hai Deewani full audio' },
  { t: 'Zinda Hoon Yaar', f: 'Lootera', y: 2013, q: 'Zinda Lootera Amitabh Bhattacharya full song' },
  { t: 'Jeene Laga Hoon', f: 'Ramaiya Vastavaiya', y: 2013 },
  { t: 'Tera Ban Jaunga', f: 'Kabir Singh', y: 2019 },
  { t: 'Khairiyat', f: 'Chhichhore', y: 2019 },
  { t: 'Fikar Not', f: 'Chhichhore', y: 2019 },
  { t: 'Bhagwan Hai Kahan Re Tu', f: 'PK', y: 2014 },
  { t: 'Nanga Punga Dost', f: 'PK', y: 2014 },
];
