// Chai Tapri — golden hour. Indie, soft-rock, the acoustic end of Bollywood.
// Nobody has anywhere to be for twenty more minutes.

export default [
  { t: 'Kabira', f: 'Yeh Jawaani Hai Deewani', y: 2013 },
  { t: 'Ilahi', f: 'Yeh Jawaani Hai Deewani', y: 2013, q: 'Ilahi full video song Yeh Jawaani Hai Deewani Arijit Singh Ranbir' },
  { t: 'Phir Le Aaya Dil', f: 'Barfi!', y: 2012 },
  { t: 'Iktara', f: 'Wake Up Sid', y: 2009 },
  { t: 'Behti Hawa Sa Tha Woh', f: '3 Idiots', y: 2009 },
  { t: 'Khoya Khoya Chand', f: 'Kala Bazar', y: 1960 },
  { t: 'Tum Ho Toh', f: 'Rock On!!', y: 2008 },
  { t: 'Masakali', f: 'Delhi-6', y: 2009 },
  { t: 'Nadaan Parindey', f: 'Rockstar', y: 2011 },
  { t: 'Bandeh', f: 'Black Friday', y: 2004, a: 'Indian Ocean' },
  { t: 'Ma Rewa', a: 'Indian Ocean' },
  { t: 'Ek Garam Chai Ki Pyali Ho', q: 'Ek Garam Chai Ki Pyali Ho Kishore Kumar old hindi song' },

  { t: 'Kandisa', a: 'Indian Ocean' },
  { t: 'Des Mera', a: 'Indian Ocean', q: 'Des Mera Indian Ocean song' },
  { t: 'Jhini Re Jhini', a: 'Indian Ocean' },
  { t: 'Socha Hai', f: 'Rock On!!', y: 2008 },
  { t: 'Pichle Saat Dinon Mein', f: 'Rock On!!', y: 2008 },
  { t: 'Rock On Title Track', f: 'Rock On!!', y: 2008, q: 'Rock On title track Farhan Akhtar full song' },
  { t: 'Sindbad The Sailor', f: 'Rock On!!', y: 2008 },
  { t: 'Meethi Boliyaan', f: 'Kai Po Che!', y: 2013 },
  { t: 'Shubhaarambh', f: 'Kai Po Che!', y: 2013 },
  { t: 'Aahatein', f: 'Agneepath', y: 2012, q: 'Aahatein Splitsvilla Agnee band song' },
  { t: 'Kabhi Jo Baadal Barse', f: 'Jackpot', y: 2013 },
  { t: 'Tu Hi Meri Shab Hai', f: 'Gangster', y: 2006 },
  { t: 'Ya Ali', f: 'Gangster', y: 2006 },
  { t: 'Aashayein', f: 'Iqbal', y: 2005 },
  { t: 'Yun Hi Chala', f: 'Swades', y: 2004, q: 'Yun Hi Chala Chal Rahi Swades Udit Narayan Kailash Kher' },
  { t: 'Allah Ke Bande', a: 'Kailash Kher', y: 2003 },
  { t: 'Teri Deewani', a: 'Kailash Kher', y: 2006 },
  { t: 'Saiyyan', a: 'Kailash Kher', y: 2006 },
  { t: 'Toota Toota Ek Parinda', a: 'Kailash Kher', y: 2006 },
  { t: 'Bulla Ki Jaana', a: 'Rabbi Shergill', y: 2004 },
  { t: 'Tere Bin', a: 'Rabbi Shergill', y: 2004 },
  { t: 'Challa', f: 'Jab Tak Hai Jaan', y: 2012 },
  { t: 'Heer', f: 'Jab Tak Hai Jaan', y: 2012 },
  { t: 'Saans', f: 'Jab Tak Hai Jaan', y: 2012 },
  { t: 'Ashq Na Ho', f: 'Jab Tak Hai Jaan', y: 2012 },
  { t: 'Sawaar Loon', f: 'Lootera', y: 2013 },
  { t: 'Manmarziyan', f: 'Lootera', y: 2013 },
  { t: 'Shikayatein', f: 'Lootera', y: 2013 },
  { t: 'Ankahee', f: 'Lootera', y: 2013 },
  { t: 'Aarambh Hai Prachand', f: 'Gulaal', y: 2009 },
  { t: 'Duniya', f: 'Gulaal', y: 2009 },
  { t: 'Ala Barfi', f: 'Barfi!', y: 2012 },
  { t: 'Main Kya Karoon', f: 'Barfi!', y: 2012 },
  { t: 'Kyon', f: 'Barfi!', y: 2012 },
  { t: 'Aashiyan', f: 'Barfi!', y: 2012 },
  { t: 'Saibo', f: 'Shor In The City', y: 2011 },
  { t: 'Piya Aaye Na', f: 'Aashiqui 2', y: 2013 },
  { t: 'Hum Mar Jayenge', f: 'Aashiqui 2', y: 2013 },
  { t: 'Chahun Main Ya Naa', f: 'Aashiqui 2', y: 2013 },
  { t: 'Tum Hi Ho', f: 'Aashiqui 2', y: 2013 },
  { t: 'Bulleya', f: 'Ae Dil Hai Mushkil', y: 2016 },
  { t: 'Channa Mereya', f: 'Ae Dil Hai Mushkil', y: 2016 },
  { t: 'Ae Dil Hai Mushkil', f: 'Ae Dil Hai Mushkil', y: 2016 },
  { t: 'Enna Sona', f: 'OK Jaanu', y: 2017 },
  { t: 'Kaun Tujhe', f: 'M.S. Dhoni: The Untold Story', y: 2016 },
  { t: 'Besabriyaan', f: 'M.S. Dhoni: The Untold Story', y: 2016 },
  { t: 'Phir Kabhi', f: 'M.S. Dhoni: The Untold Story', y: 2016 },
  { t: 'Nazm Nazm', f: 'Bareilly Ki Barfi', y: 2017 },
  { t: 'Twist Kamariya', f: 'Bareilly Ki Barfi', y: 2017 },
  { t: 'Kalank Title Track', f: 'Kalank', y: 2019 },
  { t: 'Ghar More Pardesiya', f: 'Kalank', y: 2019 },
  { t: 'Ve Maahi', f: 'Kesari', y: 2019 },
  { t: 'Teri Mitti', f: 'Kesari', y: 2019 },
  { t: 'Apna Bana Le', f: 'Bhediya', y: 2022 },
  { t: 'Kesariya', f: 'Brahmastra', y: 2022 },
  { t: 'Deva Deva', f: 'Brahmastra', y: 2022 },
  { t: 'Rait Zara Si', f: 'Atrangi Re', y: 2021 },
  { t: 'Chaka Chak', f: 'Atrangi Re', y: 2021 },
  { t: 'Shayad', f: 'Love Aaj Kal', y: 2020 },
  { t: 'Haan Main Galat', f: 'Love Aaj Kal', y: 2020 },
  { t: 'Twist', f: 'Love Aaj Kal', y: 2009 },
  { t: 'Aahun Aahun', f: 'Love Aaj Kal', y: 2009 },
  { t: 'Chor Bazaari', f: 'Love Aaj Kal', y: 2009 },
  { t: 'Dooriyan', f: 'Love Aaj Kal', y: 2009 },
  { t: 'Yeh Dooriyan', f: 'Love Aaj Kal', y: 2009, q: 'Yeh Dooriyan Love Aaj Kal Mohit Chauhan full song' },
  { t: 'Pee Loon', f: 'Once Upon A Time In Mumbaai', y: 2010 },
  { t: 'Tum Jo Aaye', f: 'Once Upon A Time In Mumbaai', y: 2010 },
  { t: 'Guzaarish', f: 'Ghajini', y: 2008 },
  { t: 'Kaise Mujhe', f: 'Ghajini', y: 2008 },
  { t: 'Aye Bachchu', f: 'Ghajini', y: 2008 },
  { t: 'Tere Bina Guru', f: 'Guru', y: 2007, q: 'Tere Bina Guru A R Rahman Chinmayi full song' },
  { t: 'Ay Hairathe', f: 'Guru', y: 2007 },
  { t: 'Mayya Mayya', f: 'Guru', y: 2007 },
  { t: 'Dil Gira Dafatan', f: 'Delhi-6', y: 2009 },
  { t: 'Genda Phool', f: 'Delhi-6', y: 2009 },
  { t: 'Bhor Bhaye', f: 'Delhi-6', y: 2009 },
  { t: 'Naina Thag Lenge', f: 'Omkara', y: 2006 },
  { t: 'O Saathi Re Omkara', f: 'Omkara', y: 2006, q: 'O Saathi Re Omkara Shreya Ghoshal full song' },
  { t: 'Jag Ja', f: 'Omkara', y: 2006 },
  { t: 'Ek Din Bik Jayega', f: 'Dharam Karam', y: 1975 },
  { t: 'Zindagi Kaisi Hai Paheli', f: 'Anand', y: 1971 },
  { t: 'Kahin Door Jab Din Dhal Jaye', f: 'Anand', y: 1971 },
  { t: 'Maine Tere Liye Hi', f: 'Anand', y: 1971 },
  { t: 'Rimjhim Gire Sawan Kishore', f: 'Manzil', y: 1979, q: 'Rimjhim Gire Sawan Kishore Kumar Manzil male version' },
];
