// Dhaba Wala — GT Road at 1am. Punjabi pop and bhangra, from the Malkit Singh
// era through Diljit and the AP Dhillon lot.

export default [
  { t: 'Mundian To Bach Ke', a: 'Panjabi MC', y: 1998 },
  { t: 'Gur Naal Ishq Mitha', a: 'Malkit Singh', q: 'Gur Nalo Ishq Mitha Malkit Singh original bhangra song' },
  { t: 'Jugni', f: 'Cocktail', y: 2012 },
  { t: 'Sadi Gali', f: 'Tanu Weds Manu', y: 2011 },
  { t: 'Kala Chashma', f: 'Baar Baar Dekho', y: 2016 },
  { t: 'Patiala Peg', a: 'Diljit Dosanjh', y: 2015 },
  { t: 'Laembadgini', a: 'Diljit Dosanjh', y: 2016 },
  { t: 'Do You Know', a: 'Diljit Dosanjh', y: 2011, q: 'Do You Know Diljit Dosanjh full punjabi song album' },
  { t: 'High Rated Gabru', a: 'Guru Randhawa', y: 2017 },
  { t: 'Lamberghini', a: 'The Doorbeen', y: 2018 },
  { t: 'Brown Munde', a: 'AP Dhillon', y: 2020 },
  { t: 'Yaar Anmulle', a: 'Sharry Mann', y: 2011 },

  { t: 'Excuses', a: 'AP Dhillon', y: 2020 },
  { t: 'Insane', a: 'AP Dhillon', y: 2021 },
  { t: 'Summer High', a: 'AP Dhillon', y: 2021 },
  { t: 'Majhail', a: 'AP Dhillon', y: 2022 },
  { t: 'With You', a: 'AP Dhillon', y: 2021 },
  { t: 'Dil Nu', a: 'AP Dhillon', y: 2022 },
  { t: 'Tere Te', a: 'AP Dhillon', y: 2022 },
  { t: 'Same Beef', a: 'Sidhu Moose Wala', y: 2019 },
  { t: 'So High', a: 'Sidhu Moose Wala', y: 2017 },
  { t: '295', a: 'Sidhu Moose Wala', y: 2021 },
  { t: 'The Last Ride', a: 'Sidhu Moose Wala', y: 2022 },
  { t: 'Legend', a: 'Sidhu Moose Wala', y: 2020 },
  { t: 'Bambiha Bole', a: 'Sidhu Moose Wala', y: 2020 },
  { t: 'Jatt Da Muqabala', a: 'Sidhu Moose Wala', y: 2018 },
  { t: 'Old Skool', a: 'Sidhu Moose Wala', y: 2020 },
  { t: 'Lamborghini Sidhu', a: 'Sidhu Moose Wala', y: 2021, q: 'Lamborghini Sidhu Moose Wala official song' },
  { t: 'GOAT', a: 'Diljit Dosanjh', y: 2020 },
  { t: 'Born To Shine', a: 'Diljit Dosanjh', y: 2020 },
  { t: 'Clash', a: 'Diljit Dosanjh', y: 2021 },
  { t: 'Lover', a: 'Diljit Dosanjh', y: 2021 },
  { t: 'Kinni Kinni', a: 'Diljit Dosanjh', y: 2023 },
  { t: 'Naina Diljit', a: 'Diljit Dosanjh', q: 'Naina Diljit Dosanjh Crew song' },
  { t: '5 Taara', a: 'Diljit Dosanjh', y: 2015 },
  { t: 'Ikk Kudi', f: 'Udta Punjab', y: 2016 },
  { t: 'Chitta Ve', f: 'Udta Punjab', y: 2016 },
  { t: 'Da Da Dasse', f: 'Udta Punjab', y: 2016 },
  { t: 'Proper Patola Dhaba', a: 'Diljit Dosanjh', y: 2013, q: 'Proper Patola Diljit Dosanjh Badshah original song' },
  { t: 'Kylie Kareena', a: 'Diljit Dosanjh', y: 2018, q: 'Kylie Kareena Diljit Dosanjh song' },
  { t: 'Suit Suit Dhaba', a: 'Guru Randhawa', y: 2017, q: 'Suit Suit Guru Randhawa Arjun original song' },
  { t: 'Ishare Tere', a: 'Guru Randhawa', y: 2018 },
  { t: 'Made In India', a: 'Guru Randhawa', y: 2018 },
  { t: 'Nach Meri Rani', a: 'Guru Randhawa', y: 2020, q: 'Naach Meri Rani Guru Randhawa Nora Fatehi song' },
  { t: 'Patola', a: 'Guru Randhawa', y: 2015 },
  { t: 'Yaar Mod Do', a: 'Guru Randhawa', y: 2016 },
  { t: 'Outfit', a: 'Guru Randhawa', y: 2016 },
  { t: 'Fashion', a: 'Guru Randhawa', y: 2017 },
  { t: 'Downtown', a: 'Guru Randhawa', y: 2018 },
  { t: 'Raat Kamaal Hai', a: 'Guru Randhawa', y: 2018 },
  { t: 'Tere Te', a: 'Guru Randhawa', y: 2019, q: 'Tere Te Guru Randhawa Jaani song' },
  { t: '3 Peg', a: 'Sharry Mann', y: 2016 },
  { t: 'Cute Munda', a: 'Sharry Mann', y: 2017 },
  { t: 'Transportiye', a: 'Sharry Mann', y: 2018 },
  { t: 'Hostel', a: 'Sharry Mann', y: 2015 },
  { t: 'Athra Athra Saal', a: 'Sharry Mann', q: 'Athra Athra Saal Sharry Mann song' },
  { t: 'Qismat', a: 'Ammy Virk', y: 2018 },
  { t: 'Sohreyan Da Pind', a: 'Ammy Virk', y: 2021 },
  { t: 'Nikle Currant Dhaba', a: 'Jassi Gill', y: 2018, q: 'Nikle Currant Jassi Gill Neha Kakkar song' },
  { t: 'Bapu Zimidar', a: 'Jassi Gill', y: 2013 },
  { t: 'Laden', a: 'Jassi Gill', y: 2014 },
  { t: 'Kya Baat Ay', a: 'Harrdy Sandhu', y: 2018 },
  { t: 'Hornn Blow', a: 'Harrdy Sandhu', y: 2016 },
  { t: 'Joker', a: 'Harrdy Sandhu', y: 2015 },
  { t: 'Yaar Naa Miley', f: 'Kick', y: 2014 },
  { t: 'Kaun Nachdi', f: 'Sonu Ke Titu Ki Sweety', y: 2018 },
  { t: 'Daru Badnaam', a: 'Kamal Kahlon', y: 2017 },
  { t: 'Wakhra Swag Dhaba', a: 'Navv Inder', y: 2015, q: 'Wakhra Swag Navv Inder Badshah original song' },
  { t: 'Bomb Jatt', a: 'Jassi Gill', q: 'Bomb Jatt Jassi Gill Babbal Rai song' },
  { t: 'Attt Karti', a: 'Jassi Gill', y: 2016 },
  { t: 'Mitran Da Naa Chalda', a: 'Babbu Maan', q: 'Mitran Da Naa Chalda Babbu Maan song' },
  { t: 'Ki Banu Duniya Da', a: 'Gurdas Maan', y: 2015 },
  { t: 'Challa Gurdas Maan', a: 'Gurdas Maan', q: 'Challa Gurdas Maan original punjabi song' },
  { t: 'Apna Punjab Hove', a: 'Gurdas Maan', q: 'Apna Punjab Hove Gurdas Maan song' },
  { t: 'Dil Da Mamla', a: 'Gurdas Maan', q: 'Dil Da Mamla Hai Gurdas Maan song' },
  { t: 'Boot Polishan', a: 'Gurdas Maan', q: 'Boot Polishan Gurdas Maan song' },
  { t: 'Punjabian Di Shaan', a: 'Mika Singh', q: 'Punjabian Di Shaan Vakhri song' },
  { t: 'Sawan Mein Lag Gayi Aag', a: 'Mika Singh', q: 'Sawan Mein Lag Gayi Aag Ginny Weds Sunny song' },
  { t: 'Jhoom Barabar Jhoom', a: 'Mika Singh', q: 'Jhoom Barabar Jhoom title track full song' },
  { t: 'Ainvayi Ainvayi Dhaba', f: 'Band Baaja Baaraat', y: 2010, q: 'Ainvayi Ainvayi Band Baaja Baaraat full song' },
  { t: 'Tunak Tunak Dhaba', a: 'Daler Mehndi', q: 'Tunak Tunak Tun Daler Mehndi full official video' },
  { t: 'Rangeelo Maro Dholna', a: 'Udit Narayan', q: 'Rangeelo Maaro Dholna Aishwarya Rai song' },
  { t: 'Dama Dam Dhaba', a: 'Rahat Fateh Ali Khan', q: 'Dama Dam Mast Qalandar Rahat Fateh Ali Khan song' },
  { t: 'Jind Mahi', a: 'Rahat Fateh Ali Khan', q: 'Jind Mahi Angrezi Beat song' },
  { t: 'Kangna', a: 'Dr Zeus', q: 'Kangna Dr Zeus punjabi song' },
  { t: 'Don’t Be Shy', a: 'Dr Zeus', q: 'Don t Be Shy Again Bala movie song' },
  { t: 'Nachle Na', f: 'Dil Juunglee', y: 2018 },
  { t: 'Morni Banke Dhaba', f: 'Badhaai Ho', y: 2018, q: 'Morni Banke Badhaai Ho Guru Randhawa Neha Kakkar' },
  { t: 'Mercy', a: 'Badshah', y: 2017 },
  { t: 'Tareefan', f: 'Veere Di Wedding', y: 2018 },
  { t: 'Aankh Marey Dhaba', f: 'Simmba', y: 2018, q: 'Aankh Marey Simmba Mika Singh Neha Kakkar full song' },
  { t: 'Jatt Ludhiyane Da', f: 'Student Of The Year 2', y: 2019 },
  { t: 'Coka', a: 'Sukh-E', y: 2019 },
  { t: 'Illegal Weapon', a: 'Garry Sandhu', y: 2017 },
  { t: 'Ban Ja Rani Dhaba', a: 'Guru Randhawa', y: 2017, q: 'Ban Ja Rani Tumhari Sulu Guru Randhawa full song' },
  { t: 'Chandigarh Mein', f: 'Good Newwz', y: 2019 },
  { t: 'Sauda Khara Khara', f: 'Good Newwz', y: 2019 },
  { t: 'Filhall', a: 'B Praak', y: 2019 },
  { t: 'Mann Bharrya', a: 'B Praak', y: 2017 },
  { t: 'Dil Tod Ke', a: 'B Praak', y: 2020 },
];
