// Gym Wala — one job, no subtlety. Training montages, sports films, desi hip
// hop and anything with a drop you can lift to.

export default [
  { t: 'Sultan Title Track', f: 'Sultan', y: 2016 },
  { t: 'Brothers Anthem', f: 'Brothers', y: 2015 },
  { t: 'Zinda', f: 'Bhaag Milkha Bhaag', y: 2013 },
  { t: 'Ziddi Dil', f: 'Mary Kom', y: 2014 },
  { t: 'Malang', f: 'Dhoom 3', y: 2013 },
  { t: 'Khalibali', f: 'Padmaavat', y: 2018 },
  { t: 'Sher Aaya Sher', f: 'Gully Boy', y: 2019 },
  { t: 'Apna Time Aayega', f: 'Gully Boy', y: 2019 },
  { t: 'Dangal Title Track', f: 'Dangal', y: 2016 },
  { t: 'Get Ready To Fight', f: 'Baaghi', y: 2016 },
  { t: 'Bhaag DK Bose', f: 'Delhi Belly', y: 2011 },
  { t: 'Chak Lein De', f: 'Chandni Chowk To China', y: 2009 },

  { t: 'Dhaakad', f: 'Dangal', y: 2016 },
  { t: 'Haanikaarak Bapu', f: 'Dangal', y: 2016 },
  { t: 'Idiot Banna', f: 'Dangal', y: 2016 },
  { t: 'Baby Ko Bass Pasand Hai', f: 'Sultan', y: 2016 },
  { t: 'Bulleya Sultan', f: 'Sultan', y: 2016, q: 'Bulleya Sultan Salman Khan Papon full song' },
  { t: 'Jag Ghoomeya Sultan', f: 'Sultan', y: 2016, q: 'Jag Ghoomeya Sultan Rahat Fateh Ali Khan full song' },
  { t: 'Bhaag Milkha Bhaag Title', f: 'Bhaag Milkha Bhaag', y: 2013, q: 'Bhaag Milkha Bhaag title track Siddharth Mahadevan' },
  { t: 'Maston Ka Jhund', f: 'Bhaag Milkha Bhaag', y: 2013 },
  { t: 'Slow Motion Angreza', f: 'Bhaag Milkha Bhaag', y: 2013 },
  { t: 'Chak De India Title', f: 'Chak De! India', y: 2007, q: 'Chak De India title track Sukhwinder Singh full song' },
  { t: 'Badal Pe Paon Hai', f: 'Chak De! India', y: 2007 },
  { t: 'Maula Mere Le Le Meri Jaan', f: 'Chak De! India', y: 2007 },
  { t: 'Kandhon Se Milte Hain Kandhe', f: 'Lakshya', y: 2004 },
  { t: 'Lakshya Title Track', f: 'Lakshya', y: 2004, q: 'Main Aisa Kyun Hoon Lakshya Hrithik Roshan full song' },
  { t: 'Main Aisa Kyun Hoon', f: 'Lakshya', y: 2004 },
  { t: 'Ziddi Dil Mary Kom', f: 'Mary Kom', y: 2014, q: 'Ziddi Dil Mary Kom Vishal Dadlani full video' },
  { t: 'Sultan Reprise', f: 'Sultan', y: 2016, q: '440 Volt Sultan Mika Singh full song' },
  { t: 'Kar Har Maidaan Fateh', f: 'Sanju', y: 2018 },
  { t: 'Mere Gully Mein', f: 'Gully Boy', y: 2019 },
  { t: 'Azadi', f: 'Gully Boy', y: 2019 },
  { t: 'Jingostan', f: 'Gully Boy', y: 2019 },
  { t: 'India 91', f: 'Gully Boy', y: 2019 },
  { t: 'Asli Hip Hop', f: 'Gully Boy', y: 2019 },
  { t: 'Train Song Bandeya', f: 'Gully Boy', y: 2019, q: 'Doori Gully Boy Ranveer Singh full song' },
  { t: 'Kohinoor', a: 'DIVINE', y: 2019 },
  { t: 'Chal Bombay', a: 'DIVINE', y: 2019 },
  { t: 'Jungli Sher', a: 'DIVINE', y: 2016 },
  { t: 'Farak', a: 'DIVINE', y: 2017 },
  { t: 'Machayenge', a: 'Emiway Bantai', y: 2019 },
  { t: 'Aur Bantai', a: 'Emiway Bantai', y: 2017 },
  { t: 'Firse Machayenge', a: 'Emiway Bantai', y: 2020 },
  { t: 'Zinda Banda', f: 'Jawan', y: 2023 },
  { t: 'Not Ramaiya Vastavaiya', f: 'Jawan', y: 2023 },
  { t: 'Chaleya', f: 'Jawan', y: 2023 },
  { t: 'Jhoome Jo Pathaan', f: 'Pathaan', y: 2023 },
  { t: 'Besharam Rang', f: 'Pathaan', y: 2023 },
  { t: 'Pathaan Title Track', f: 'Pathaan', y: 2023, q: 'Pathaan title track BGM Jhoome Jo Pathaan song' },
  { t: 'Tiger Zinda Hai Theme', f: 'Tiger Zinda Hai', y: 2017, q: 'Zinda Hai Tiger Zinda Hai Sukhwinder Singh full song' },
  { t: 'Dhoom Machale Dhoom', f: 'Dhoom 3', y: 2013 },
  { t: 'Kamli', f: 'Dhoom 3', y: 2013 },
  { t: 'Dhoom Tap', f: 'Dhoom 3', y: 2013 },
  { t: 'Bang Bang Title Track', f: 'Bang Bang!', y: 2014 },
  { t: 'Meherbaan', f: 'Bang Bang!', y: 2014 },
  { t: 'Tu Meri', f: 'Bang Bang!', y: 2014 },
  { t: 'War Theme', f: 'War', y: 2019, q: 'Jai Jai Shivshankar War Hrithik Tiger full song' },
  { t: 'Malang Title Track', f: 'Malang', y: 2020 },
  { t: 'Humraah', f: 'Malang', y: 2020 },
  { t: 'Chal Ghar Chalen', f: 'Malang', y: 2020 },
  { t: 'Baaghi Theme', f: 'Baaghi 2', y: 2018, q: 'Get Ready To Fight Baaghi 2 Benny Dayal full song' },
  { t: 'Mundiyan', f: 'Baaghi 2', y: 2018 },
  { t: 'Sadda Haq Rockstar', f: 'Rockstar', y: 2011, q: 'Sadda Haq Rockstar Mohit Chauhan full song' },
  { t: 'Rock On Rock On', f: 'Rock On 2', y: 2016, q: 'Jaago Rock On 2 Farhan Akhtar full song' },
  { t: 'Zehnaseeb', f: 'Hasee Toh Phasee', y: 2014 },
  { t: 'Manja Kai Po Che', f: 'Kai Po Che!', y: 2013, q: 'Manja Kai Po Che Amit Trivedi full song' },
  { t: 'Sultan Ka Sher', f: 'Sultan', y: 2016, q: 'Sultan title track Sukhwinder Singh full video' },
  { t: 'Aala Re Aala', f: 'Simmba', y: 2018 },
  { t: 'Singham Theme', f: 'Singham', y: 2011, q: 'Singham title track Ajay Devgn Sukhwinder full song' },
  { t: 'Hanuman Chalisa Rock', a: 'Bhajan', q: 'Hanuman Chalisa rock version instrumental' },
  { t: 'Aila Re Aillaa', f: 'Sooryavanshi', y: 2021 },
  { t: 'Naatu Naatu', f: 'RRR', y: 2022 },
  { t: 'Komuram Bheemudo', f: 'RRR', y: 2022, q: 'Komuram Bheemudo RRR Hindi version song' },
  { t: 'Dosti RRR', f: 'RRR', y: 2022, q: 'Dosti RRR Hindi song Amit Trivedi' },
  { t: 'Jai Sri Ram RRR', f: 'RRR', y: 2022, q: 'Raamam Raaghavam RRR Hindi song' },
  { t: 'Jiyo Re Bahubali', f: 'Baahubali 2', y: 2017 },
  { t: 'Manohari', f: 'Baahubali', y: 2015, q: 'Manohari Bahubali Hindi song full' },
  { t: 'Dhivara', f: 'Baahubali', y: 2015, q: 'Dhivara Bahubali Hindi song full' },
  { t: 'Toofan Title Track', f: 'Toofaan', y: 2021, q: 'Todun Taak Toofaan Farhan Akhtar song' },
  { t: 'Star Hai Tu', f: 'Toofaan', y: 2021, q: 'Toofaan title track Farhan Akhtar full song' },
  { t: 'Sooraj Dooba Hain', f: 'Roy', y: 2015 },
  { t: 'Ziddi', f: 'Mary Kom', y: 2014, q: 'Sudhir Mary Kom motivational song' },
  { t: 'Saibo Gym Mix', f: 'Shor In The City', y: 2011, q: 'Karma Is A Bitch Shor In The City song' },
  { t: 'Dum Dum', f: 'Band Baaja Baaraat', y: 2010 },
  { t: 'Ainvayi Ainvayi', f: 'Band Baaja Baaraat', y: 2010 },
  { t: 'Sadi Gali Gym', f: 'Tanu Weds Manu', y: 2011, q: 'Sadi Gali Tanu Weds Manu Lehmber Hussainpuri full song' },
];
