// Mandir Wala — 5am, bell and loudspeaker. Aartis, bhajans, mantras and the
// devotional side of the film catalogue.

export default [
  { t: 'Om Jai Jagdish Hare', q: 'Om Jai Jagdish Hare aarti' },
  { t: 'Achyutam Keshavam', a: 'Bhajan' },
  { t: 'Hanuman Chalisa', a: 'Hariharan', q: 'Shree Hanuman Chalisa Hariharan Gulshan Kumar' },
  { t: 'Gayatri Mantra', a: 'Anuradha Paudwal' },
  { t: 'Aisi Lagi Lagan', a: 'Anup Jalota' },
  { t: 'Jai Ganesh Deva', q: 'Jai Ganesh Deva aarti' },
  { t: 'Sukhkarta Dukhharta', q: 'Sukhkarta Dukhharta Ganpati aarti' },
  { t: 'Raghupati Raghav Raja Ram', q: 'Raghupati Raghav Raja Ram bhajan' },
  { t: 'Vaishnav Jan To', q: 'Vaishnav Jan To Tene Kahiye bhajan' },
  { t: 'Man Tarpat Hari Darshan Ko Aaj', f: 'Baiju Bawra', y: 1952, q: 'Man Tarpat Hari Darshan Ko Aaj Mohammed Rafi Baiju Bawra' },
  { t: 'Allah Tero Naam', f: 'Hum Dono', y: 1961, q: 'Allah Tero Naam Ishwar Tero Naam Lata Mangeshkar Hum Dono original' },
  { t: 'Tu Pyar Ka Sagar Hai', f: 'Seema', y: 1955 },

  { t: 'Om Namah Shivaya', q: 'Om Namah Shivaya chant bhajan' },
  { t: 'Shiv Tandav Stotram', q: 'Shiv Tandav Stotram Shankar Mahadevan' },
  { t: 'Mahamrityunjaya Mantra', q: 'Mahamrityunjaya Mantra 108 times' },
  { t: 'Om Namo Bhagavate Vasudevaya', q: 'Om Namo Bhagavate Vasudevaya mantra' },
  { t: 'Shri Ram Chandra Kripalu', q: 'Shri Ramchandra Kripalu Bhajman bhajan' },
  { t: 'Ram Siya Ram', f: 'Adipurush', y: 2023 },
  { t: 'Shri Ram Janki', q: 'Shri Ram Janki Baithe Hain Mere Seene Mein bhajan' },
  { t: 'Hanuman Aarti', q: 'Aarti Kije Hanuman Lala Ki aarti' },
  { t: 'Bajrang Baan', q: 'Bajrang Baan Hanuman path' },
  { t: 'Ram Naam Ke Heere Moti', q: 'Ram Naam Ke Heere Moti bhajan' },
  { t: 'Jai Jai Shiv Shankar', f: 'Aap Ki Kasam', y: 1974 },
  { t: 'Mere Ghar Ram Aaye Hain', q: 'Mere Ghar Ram Aaye Hain bhajan Jubin Nautiyal' },
  { t: 'Shyam Teri Bansi', f: 'Geet Gaata Chal', y: 1975 },
  { t: 'Itni Shakti Hamein Dena Data', f: 'Ankush', y: 1986 },
  { t: 'Tumhi Ho Mata', f: 'Main Chup Rahungi', y: 1962 },
  { t: 'Ae Malik Tere Bande Hum', f: 'Do Aankhen Barah Haath', y: 1957 },
  { t: 'Insaaf Ka Mandir Hai', f: 'Amar', y: 1954 },
  { t: 'O Palan Haare', f: 'Lagaan', y: 2001 },
  { t: 'Radha Kaise Na Jale', f: 'Lagaan', y: 2001 },
  { t: 'Achyutam Keshavam Kripalu', a: 'Kirtan', q: 'Achyutam Keshavam Krishna Damodaram bhajan full' },
  { t: 'Hare Krishna Hare Rama', q: 'Hare Krishna Hare Rama maha mantra kirtan' },
  { t: 'Govind Bolo Hari Gopal Bolo', q: 'Govind Bolo Hari Gopal Bolo bhajan' },
  { t: 'Jai Radha Madhav', q: 'Jai Radha Madhav kirtan bhajan' },
  { t: 'Shree Krishna Govind Hare Murari', q: 'Shree Krishna Govind Hare Murari Jagjit Singh' },
  { t: 'Madhurashtakam', q: 'Madhurashtakam Adharam Madhuram bhajan' },
  { t: 'Yashomati Maiya Se', f: 'Satyam Shivam Sundaram', y: 1978 },
  { t: 'Satyam Shivam Sundaram', f: 'Satyam Shivam Sundaram', y: 1978 },
  { t: 'Bhor Bhaye Panghat Pe', f: 'Satyam Shivam Sundaram', y: 1978 },
  { t: 'Payoji Maine Ram Ratan', a: 'Lata Mangeshkar', q: 'Payoji Maine Ram Ratan Dhan Payo Lata Mangeshkar' },
  { t: 'Jo Bhaje Hari Ko Sada', f: 'Baiju Bawra', y: 1952 },
  { t: 'O Duniya Ke Rakhwale', f: 'Baiju Bawra', y: 1952 },
  { t: 'Tu Ganga Ki Mauj', f: 'Baiju Bawra', y: 1952 },
  { t: 'Darshan Do Ghanshyam', f: 'Narsi Bhagat', y: 1957 },
  { t: 'Prabhu Tero Naam', f: 'Hum Dono', y: 1961 },
  { t: 'Aye Malik Tere Bande', a: 'Bhajan', q: 'Ae Malik Tere Bande Hum school prayer song' },
  { t: 'Hey Ram Hey Ram', a: 'Jagjit Singh', q: 'Hey Ram Hey Ram Jagjit Singh bhajan' },
  { t: 'Sarva Mangala Mangalye', q: 'Sarva Mangala Mangalye Durga mantra' },
  { t: 'Ambe Tu Hai Jagdambe', q: 'Ambe Tu Hai Jagdambe Kali aarti' },
  { t: 'Jai Ambe Gauri', q: 'Jai Ambe Gauri aarti Durga' },
  { t: 'Chalo Bulawa Aaya Hai', q: 'Chalo Bulawa Aaya Hai Mata Ne Bulaya Hai bhajan' },
  { t: 'Bhar Do Jholi Meri Mata', q: 'Mehndipur Balaji bhajan Bhar Do Jholi' },
  { t: 'Maa Sherawali', q: 'Maa Sherawaliye bhajan Narendra Chanchal' },
  { t: 'Namo Namo Shankara', f: 'Kedarnath', y: 2018 },
  { t: 'Shiv Shambho', q: 'Shiv Shambho Mahadeva bhajan' },
  { t: 'Bam Bam Bhole', f: 'Bhole Baba', q: 'Bam Bam Bhole kanwar bhajan song' },
  { t: 'Damroo Wale', q: 'Damroo Wala Aaya Shiv bhajan' },
  { t: 'Om Sai Ram', q: 'Om Sai Ram Sai Baba bhajan aarti' },
  { t: 'Sai Baba Aarti', q: 'Sai Baba Aarti Sai Ram Sai Shyam' },
  { t: 'Deva Shree Ganesha', f: 'Agneepath', y: 2012 },
  { t: 'Sadda Dil Vi Tu', f: 'ABCD', y: 2013, q: 'Sadda Dil Vi Tu Ga Ga Ganpati ABCD song' },
  { t: 'Shendur Laal Chadhayo', q: 'Shendur Laal Chadhayo Ganpati aarti' },
  { t: 'Ganpati Bappa Morya', q: 'Ganpati Bappa Morya aarti song' },
  { t: 'Mangal Bhavan Amangal Haari', q: 'Mangal Bhavan Amangal Haari Ramayan chaupai' },
  { t: 'Achutam Keshavam Rama', a: 'Bhajan', q: 'Achyutam Keshavam bhajan Sounds of Isha' },
  { t: 'Aigiri Nandini', q: 'Aigiri Nandini Mahishasura Mardini Stotram' },
  { t: 'Lingashtakam', q: 'Lingashtakam Brahma Murari bhajan' },
  { t: 'Shiv Chalisa', q: 'Shiv Chalisa full path bhajan' },
  { t: 'Durga Chalisa', q: 'Durga Chalisa full path bhajan' },
  { t: 'Ganesh Chalisa', q: 'Ganesh Chalisa full path bhajan' },
  { t: 'Krishna Bhajan Shyam', a: 'Jubin Nautiyal', q: 'Shyam Teri Bansi Pukare Radha Naam bhajan' },
  { t: 'Kanha Soja Zara', f: 'Bahubali 2', y: 2017 },
  { t: 'Woh Kisna Hai', f: 'Kisna', y: 2005 },
  { t: 'Mann Mohana', f: 'Jodhaa Akbar', y: 2008 },
  { t: 'Piya Tose Naina Lage Re', f: 'Guide', y: 1965 },
  { t: 'Kanha Re', a: 'Shreya Ghoshal', q: 'Kanha Re Shreya Ghoshal bhajan song' },
  { t: 'Ya Devi Sarva Bhuteshu', q: 'Ya Devi Sarva Bhuteshu mantra Durga' },
  { t: 'Om Bhur Bhuva Swaha', q: 'Gayatri Mantra 108 times chant' },
  { t: 'Asato Ma Sadgamaya', q: 'Asato Ma Sadgamaya shanti mantra' },
  { t: 'Twameva Mata', q: 'Twameva Mata Cha Pita Twameva shloka' },
  { t: 'Guru Brahma Guru Vishnu', q: 'Guru Brahma Guru Vishnu guru mantra' },
  { t: 'Achyuta Ashtakam', q: 'Achyutashtakam Achyutam Keshavam Rama Narayanam' },
  { t: 'Sri Suktam', q: 'Sri Suktam Lakshmi mantra chant' },
  { t: 'Kanakadhara Stotram', q: 'Kanakadhara Stotram Lakshmi stotra' },
  { t: 'Vishnu Sahasranamam', q: 'Vishnu Sahasranamam full chant' },
  { t: 'Nirvana Shatakam', q: 'Nirvana Shatakam Chidananda Roopah Shivoham' },
  { t: 'Ek Onkar', f: 'Rang De Basanti', y: 2006 },
  { t: 'Ik Onkar Satnam', a: 'Harshdeep Kaur', q: 'Ik Onkar Rang De Basanti Harshdeep Kaur full song' },
  { t: 'Satnam Waheguru', q: 'Satnam Waheguru simran shabad' },
  { t: 'Tu Thakur Tum Peh Ardas', q: 'Tu Thakur Tum Peh Ardas shabad gurbani' },
  { t: 'Deh Shiva Bar Mohe', q: 'Deh Shiva Bar Mohe Ihe shabad' },
  { t: 'Aarti Kunj Bihari Ki', q: 'Aarti Kunj Bihari Ki Krishna aarti' },
];
