// Paan Wala — the transistor on the shelf. Eighties masala, disco, cabaret and
// the Bappi/Laxmikant-Pyarelal end of the catalogue.

export default [
  { t: 'Khaike Paan Banaraswala', f: 'Don', y: 1978 },
  { t: 'I Am A Disco Dancer', f: 'Disco Dancer', y: 1982 },
  { t: 'Jimmy Jimmy Aaja', f: 'Disco Dancer', y: 1982 },
  { t: 'Ui Amma Ui Amma', f: 'Mawaali', y: 1983 },
  { t: 'Aap Jaisa Koi', f: 'Qurbani', y: 1980 },
  { t: 'Jawani Janeman', f: 'Namak Halaal', y: 1982 },
  { t: 'Pag Ghungroo Baandh', f: 'Namak Halaal', y: 1982 },
  { t: 'Ek Do Teen', f: 'Tezaab', y: 1988 },
  { t: 'Papa Kehte Hain', f: 'Qayamat Se Qayamat Tak', y: 1988 },
  { t: 'Tirchi Topiwale', f: 'Tridev', y: 1989 },
  { t: 'Oye Oye', f: 'Tridev', y: 1989 },
  { t: 'Yaad Aa Raha Hai', f: 'Disco Dancer', y: 1982 },

  { t: 'Auva Auva Koi Yahan Nache', f: 'Disco Dancer', y: 1982 },
  { t: 'Goro Ki Na Kalo Ki', f: 'Disco Dancer', y: 1982 },
  { t: 'Krishna Dharti Pe Aaja Tu', f: 'Disco Dancer', y: 1982 },
  { t: 'Super Dancer', f: 'Dance Dance', y: 1987 },
  { t: 'Zooby Zooby', f: 'Dance Dance', y: 1987 },
  { t: 'Aaja Aaja Meri Bahon Mein', f: 'Dance Dance', y: 1987 },
  { t: 'Kasam Paida Karne Wale Ki', f: 'Kasam Paida Karne Wale Ki', y: 1984 },
  { t: 'Yaar Bina Chain Kahan Re', f: 'Saaheb', y: 1985 },
  { t: 'Tamma Tamma Loge Paan', f: 'Thanedaar', y: 1990, q: 'Tamma Tamma Loge Thanedaar Bappi Lahiri original song' },
  { t: 'De De Pyar De', f: 'Sharaabi', y: 1984 },
  { t: 'Log Kehte Hain Main Sharabi Hoon', f: 'Sharaabi', y: 1984 },
  { t: 'Jahan Char Yaar', f: 'Sharaabi', y: 1984 },
  { t: 'Rang Barse Bhige Chunar Wali', f: 'Silsila', y: 1981 },
  { t: 'Dekha Ek Khwab', f: 'Silsila', y: 1981 },
  { t: 'Yeh Kahan Aa Gaye Hum', f: 'Silsila', y: 1981 },
  { t: 'Neela Aasman So Gaya', f: 'Silsila', y: 1981 },
  { t: 'Mere Angne Mein', f: 'Laawaris', y: 1981 },
  { t: 'Kab Ke Bichhde Hue', f: 'Laawaris', y: 1981 },
  { t: 'Apni To Jaise Taise', f: 'Laawaris', y: 1981 },
  { t: 'Jumma Chumma De De', f: 'Hum', y: 1991 },
  { t: 'Ek Doosre Se Karte Hain Pyar', f: 'Hum', y: 1991 },
  { t: 'Sanam Mere Sanam', f: 'Hum', y: 1991 },
  { t: 'Aaj Rapat Jaaye', f: 'Namak Halaal', y: 1982 },
  { t: 'Raat Baaki Baat Baaki', f: 'Namak Halaal', y: 1982 },
  { t: 'Thodi Si Jo Pee Li Hai', f: 'Namak Halaal', y: 1982 },
  { t: 'Yaari Hai Imaan Mera', f: 'Zanjeer', y: 1973 },
  { t: 'Dil Jalon Ka Dil Jala Ke', f: 'Zanjeer', y: 1973 },
  { t: 'Mehbooba Mehbooba', f: 'Sholay', y: 1975 },
  { t: 'Koi Haseena', f: 'Sholay', y: 1975 },
  { t: 'Holi Ke Din', f: 'Sholay', y: 1975 },
  { t: 'Jab Tak Hai Jaan', f: 'Sholay', y: 1975 },
  { t: 'My Name Is Anthony Gonsalves', f: 'Amar Akbar Anthony', y: 1977 },
  { t: 'Shirdi Wale Sai Baba', f: 'Amar Akbar Anthony', y: 1977 },
  { t: 'Humko Tumse Ho Gaya Hai Pyar', f: 'Amar Akbar Anthony', y: 1977 },
  { t: 'Tayyab Ali Pyar Ka Dushman', f: 'Amar Akbar Anthony', y: 1977 },
  { t: 'Khaike Paan Don Remix', f: 'Don', y: 1978, q: 'Khaike Paan Banaraswala Don 1978 Kishore Kumar original' },
  { t: 'Yeh Mera Dil', f: 'Don', y: 1978 },
  { t: 'Are Diwano Mujhe Pehchano', f: 'Don', y: 1978 },
  { t: 'Ek Chatur Naar', f: 'Padosan', y: 1968 },
  { t: 'Mere Saamne Wali Khidki', f: 'Padosan', y: 1968 },
  { t: 'Kehna Hai', f: 'Padosan', y: 1968 },
  { t: 'Piya Tu Ab To Aaja', f: 'Caravan', y: 1971 },
  { t: 'Monica O My Darling', f: 'Caravan', y: 1971 },
  { t: 'Chadti Jawani Meri Chaal', f: 'Caravan', y: 1971 },
  { t: 'Duniya Mein Logon Ko Paan', f: 'Apna Desh', y: 1972, q: 'Duniya Mein Logon Ko Apna Desh Asha Bhosle Kishore' },
  { t: 'Aaja Aaja Main Hoon Pyar Tera', f: 'Teesri Manzil', y: 1966 },
  { t: 'O Haseena Zulfonwali', f: 'Teesri Manzil', y: 1966 },
  { t: 'Deewana Mujhsa Nahin', f: 'Teesri Manzil', y: 1966 },
  { t: 'Tumne Mujhe Dekha', f: 'Teesri Manzil', y: 1966 },
  { t: 'Dekha Na Haye Re', f: 'Bombay To Goa', y: 1972 },
  { t: 'Yeh Dil Na Hota Bechara', f: 'Jewel Thief', y: 1967 },
  { t: 'Hothon Pe Aisi Baat', f: 'Jewel Thief', y: 1967 },
  { t: 'Raat Akeli Hai', f: 'Jewel Thief', y: 1967 },
  { t: 'Aasman Se Aaya Farishta', f: 'An Evening In Paris', y: 1967 },
  { t: 'Yeh Chaand Sa Roshan Chehra', f: 'Kashmir Ki Kali', y: 1964 },
  { t: 'Taarif Karoon Kya Uski', f: 'Kashmir Ki Kali', y: 1964 },
  { t: 'Deewana Hua Badal', f: 'Kashmir Ki Kali', y: 1964 },
  { t: 'Jaan Pehechan Ho', f: 'Gumnaam', y: 1965 },
  { t: 'Gumnaam Hai Koi', f: 'Gumnaam', y: 1965 },
  { t: 'Aaj Ki Raat Koi Aane Ko Hai', f: 'Anamika', y: 1973 },
  { t: 'Bahon Mein Chale Aao', f: 'Anamika', y: 1973 },
  { t: 'Jaan-E-Jaan Dhoondta', f: 'Jawani Diwani', y: 1972 },
  { t: 'Nahin Nahin Abhi Nahin', f: 'Jawani Diwani', y: 1972 },
  { t: 'Saamne Yeh Kaun Aaya', f: 'Jawani Diwani', y: 1972 },
  { t: 'Yeh Jawaani Hai Deewani Paan', f: 'Jawani Diwani', y: 1972, q: 'Yeh Jawani Hai Deewani 1972 Kishore Kumar title song' },
  { t: 'Mere Naseeb Mein', f: 'Naseeb', y: 1981 },
  { t: 'John Jaani Janardhan', f: 'Naseeb', y: 1981 },
  { t: 'Chal Chal Mere Bhai', f: 'Naseeb', y: 1981 },
  { t: 'Zindagi Imtihaan Leti Hai', f: 'Naseeb', y: 1981 },
  { t: 'Om Shanti Om Paan', f: 'Karz', y: 1980, q: 'Om Shanti Om Karz 1980 Kishore Kumar original song' },
  { t: 'Dard-E-Dil', f: 'Karz', y: 1980 },
  { t: 'Ek Haseena Thi', f: 'Karz', y: 1980 },
  { t: 'Paisa Yeh Paisa', f: 'Karz', y: 1980 },
  { t: 'Sara Zamana', f: 'Yaarana', y: 1981, q: 'Sara Zamana Haseeno Ka Deewana Yaarana Kishore Kumar' },
  { t: 'Bane Chahe Dushman', f: 'Dostana', y: 1980 },
  { t: 'Mere Dost Kissa Ye', f: 'Dostana', y: 1980 },
  { t: 'Salamat Rahe Dostana', f: 'Dostana', y: 1980 },
  { t: 'Pyar Karne Wale', f: 'Shaan', y: 1980 },
  { t: 'Yamma Yamma', f: 'Shaan', y: 1980 },
  { t: 'Doston Se Pyar Kiya', f: 'Shaan', y: 1980 },
  { t: 'Jab Chhaye Mera Jadoo', f: 'Lootmaar', y: 1980 },
  { t: 'Hari Om Hari', f: 'Pyaara Dushman', y: 1980 },
  { t: 'Sun Sun Sun Didi', f: 'Aaj Ka Arjun', y: 1990 },
  { t: 'Gori Hai Kalaiyaan', f: 'Aaj Ka Arjun', y: 1990 },
  { t: 'Choli Ke Peeche', f: 'Khalnayak', y: 1993 },
  { t: 'Nayak Nahi Khalnayak', f: 'Khalnayak', y: 1993 },
  { t: 'Palki Pe Hoke Sawar', f: 'Khalnayak', y: 1993 },
  { t: 'Aaja Sajan Aaja', f: 'Khalnayak', y: 1993 },
];
