// Padhai Wala — one lamp, one desk, 2am. Soft enough to keep going, sad enough
// to feel like it matters. Nothing with a drop.

export default [
  { t: 'Tum Ho', f: 'Rockstar', y: 2011 },
  { t: 'Agar Tum Saath Ho', f: 'Tamasha', y: 2015 },
  { t: 'Khamoshiyan', f: 'Khamoshiyan', y: 2015 },
  { t: 'Tere Bina', f: 'Guru', y: 2007 },
  { t: 'Luka Chuppi', f: 'Rang De Basanti', y: 2006 },
  { t: 'Ae Ajnabi', f: 'Dil Se..', y: 1998 },
  { t: 'Naina Da Kya Kasoor', f: 'Andhadhun', y: 2018 },
  { t: 'Raabta', f: 'Agent Vinod', y: 2012 },
  { t: 'Hasi', f: 'Hamari Adhuri Kahani', y: 2015 },
  { t: 'Jag Ghoomeya', f: 'Sultan', y: 2016, q: 'Jag Ghoomeya Sultan Rahat Fateh Ali Khan full song Salman Anushka' },
  { t: 'Manja', f: 'Kai Po Che!', y: 2013 },
  { t: 'Kho Gaye Hum Kahan', f: 'Baar Baar Dekho', y: 2016 },

  { t: 'Tum Ho Paas Mere', f: 'Rockstar', y: 2011, q: 'Tum Ho Rockstar Mohit Chauhan Suzanne full song' },
  { t: 'Aur Ho', f: 'Rockstar', y: 2011 },
  { t: 'Katiya Karun', f: 'Rockstar', y: 2011 },
  { t: 'Tum Tak', f: 'Raanjhanaa', y: 2013 },
  { t: 'Piya Milenge', f: 'Raanjhanaa', y: 2013 },
  { t: 'Tu Mun Shudi', f: 'Raanjhanaa', y: 2013 },
  { t: 'Banarasiya', f: 'Raanjhanaa', y: 2013 },
  { t: 'Raanjhanaa Title Track', f: 'Raanjhanaa', y: 2013, q: 'Raanjhanaa title track Jaswinder Singh Shiraz Uppal' },
  { t: 'Iktara Female', f: 'Wake Up Sid', y: 2009, q: 'Iktara Wake Up Sid Kavita Seth Amit Trivedi full song' },
  { t: 'Wake Up Sid Title', f: 'Wake Up Sid', y: 2009, q: 'Wake Up Sid title track Shankar Mahadevan full song' },
  { t: 'Aazaadiyan', f: 'Udaan', y: 2010 },
  { t: 'Kahaani', f: 'Udaan', y: 2010, q: 'Kahaani Udaan Amit Trivedi Amitabh Bhattacharya' },
  { t: 'Geet Mein Dhalte', f: 'Udaan', y: 2010, q: 'Geet Mein Dhalte Lafzon Ka Udaan song' },
  { t: 'Naav', f: 'Udaan', y: 2010 },
  { t: 'Pardesi', f: 'Dev.D', y: 2009 },
  { t: 'Nayan Tarse', f: 'Dev.D', y: 2009 },
  { t: 'Aankh Micholi', f: 'Dev.D', y: 2009 },
  { t: 'Duniya Dev D', f: 'Dev.D', y: 2009, q: 'Duniya Dev D Amit Trivedi full song' },
  { t: 'Sooha Saha Padhai', f: 'Highway', y: 2014, q: 'Sooha Saaha Highway Alia Bhatt Zeb Bangash full song' },
  { t: 'Heera', f: 'Highway', y: 2014 },
  { t: 'Tu Kuja', f: 'Highway', y: 2014 },
  { t: 'Phir Le Aya Dil Reprise', f: 'Barfi!', y: 2012, q: 'Phir Le Aya Dil Reprise Arijit Singh Barfi full song' },
  { t: 'Saawali Si Raat', f: 'Barfi!', y: 2012 },
  { t: 'Ala Barfi Padhai', f: 'Barfi!', y: 2012, q: 'Ala Barfi Mohit Chauhan Pritam full song' },
  { t: 'Itni Si Hasi', f: 'Barfi!', y: 2012, q: 'Aashiyan Barfi Nikhil Paul George Shreya full song' },
  { t: 'Tera Yaar Hoon Main', f: 'Sonu Ke Titu Ki Sweety', y: 2018 },
  { t: 'Bol Do Na Zara', f: 'Azhar', y: 2016 },
  { t: 'Ae Dil Hai Mushkil Title', f: 'Ae Dil Hai Mushkil', y: 2016, q: 'Ae Dil Hai Mushkil title track Arijit Singh full song' },
  { t: 'Humdard', f: 'Ek Villain', y: 2014 },
  { t: 'Banjaara', f: 'Ek Villain', y: 2014 },
  { t: 'Galliyan', f: 'Ek Villain', y: 2014 },
  { t: 'Zaroorat', f: 'Ek Villain', y: 2014 },
  { t: 'Muskurane Ki Wajah', f: 'CityLights', y: 2014 },
  { t: 'Sone Do', f: 'CityLights', y: 2014 },
  { t: 'Tum Hi Ho Padhai', f: 'Aashiqui 2', y: 2013, q: 'Tum Hi Ho Aashiqui 2 Arijit Singh full song' },
  { t: 'Bhula Dena', f: 'Aashiqui 2', y: 2013 },
  { t: 'Milne Hai Mujhse Aayi', f: 'Aashiqui 2', y: 2013 },
  { t: 'Meri Aashiqui', f: 'Aashiqui 2', y: 2013 },
  { t: 'Kabira Encore', f: 'Yeh Jawaani Hai Deewani', y: 2013, q: 'Kabira Encore Yeh Jawaani Hai Deewani Arijit Harshdeep' },
  { t: 'Subhanallah', f: 'Yeh Jawaani Hai Deewani', y: 2013 },
  { t: 'Judaai', f: 'Badlapur', y: 2015 },
  { t: 'Jee Karda', f: 'Badlapur', y: 2015 },
  { t: 'Jeena Jeena', f: 'Badlapur', y: 2015 },
  { t: 'Sooraj Ki Baahon Mein Padhai', f: 'Zindagi Na Milegi Dobara', y: 2011, q: 'Sooraj Ki Baahon Mein Zindagi Na Milegi Dobara full song' },
  { t: 'Iktara Reprise', f: 'Wake Up Sid', y: 2009, q: 'Iktara reprise Wake Up Sid Tochi Raina full song' },
  { t: 'Safarnama Padhai', f: 'Tamasha', y: 2015, q: 'Safarnama Tamasha Lucky Ali A R Rahman full audio' },
  { t: 'Tu Koi Aur Hai', f: 'Tamasha', y: 2015 },
  { t: 'Wat Wat Wat', f: 'Tamasha', y: 2015 },
  { t: 'Naina', f: 'Dangal', y: 2016 },
  { t: 'Gilehriyaan', f: 'Dangal', y: 2016 },
  { t: 'Phir Se Ud Chala Padhai', f: 'Rockstar', y: 2011, q: 'Phir Se Ud Chala Rockstar Mohit Chauhan full song' },
  { t: 'Ilahi Padhai', f: 'Yeh Jawaani Hai Deewani', y: 2013, q: 'Ilahi Arijit Singh Yeh Jawaani Hai Deewani full video' },
  { t: 'Khairiyat Padhai', f: 'Chhichhore', y: 2019, q: 'Khairiyat Chhichhore Arijit Singh full song' },
  { t: 'Woh Din', f: 'Chhichhore', y: 2019 },
  { t: 'Control', f: 'Chhichhore', y: 2019 },
  { t: 'Kal Ki Hi Baat Hai', f: 'Chhichhore', y: 2019 },
  { t: 'Tujhe Kitna Chahne Lage', f: 'Kabir Singh', y: 2019 },
  { t: 'Kaise Hua Padhai', f: 'Kabir Singh', y: 2019, q: 'Kaise Hua Kabir Singh Vishal Mishra full song' },
  { t: 'Kalank Title Padhai', f: 'Kalank', y: 2019, q: 'Kalank title track Arijit Singh full song' },
  { t: 'Shayad Padhai', f: 'Love Aaj Kal', y: 2020, q: 'Shayad Love Aaj Kal Arijit Singh full song' },
  { t: 'Dil Bechara Title', f: 'Dil Bechara', y: 2020 },
  { t: 'Taare Ginn', f: 'Dil Bechara', y: 2020 },
  { t: 'Khulke Jeene Ka', f: 'Dil Bechara', y: 2020 },
  { t: 'Main Tumhara', f: 'Dil Bechara', y: 2020 },
  { t: 'Raataan Lambiyan', f: 'Shershaah', y: 2021 },
  { t: 'Ranjha', f: 'Shershaah', y: 2021 },
  { t: 'Mann Bharryaa 2.0', f: 'Shershaah', y: 2021 },
  { t: 'Kesariya Padhai', f: 'Brahmastra', y: 2022, q: 'Kesariya Brahmastra Arijit Singh full song' },
  { t: 'Rasiya', f: 'Brahmastra', y: 2022 },
  { t: 'Apna Bana Le Padhai', f: 'Bhediya', y: 2022, q: 'Apna Bana Le Bhediya Arijit Singh Sachin Jigar full song' },
  { t: 'Tum Kya Mile Padhai', f: 'Rocky Aur Rani Kii Prem Kahaani', y: 2023, q: 'Tum Kya Mile Arijit Singh Shreya Ghoshal full song' },
  { t: 'Satranga', f: 'Animal', y: 2023 },
  { t: 'O Maahi', f: 'Dunki', y: 2023 },
  { t: 'Lutt Putt Gaya', f: 'Dunki', y: 2023 },
  { t: 'Chaleya Padhai', f: 'Jawan', y: 2023, q: 'Chaleya Jawan Arijit Singh Shilpa Rao full song' },
  { t: 'Heeriye', a: 'Jasleen Royal', y: 2023 },
  { t: 'Sajni Padhai', f: 'Laapataa Ladies', y: 2024, q: 'Sajni Laapataa Ladies Arijit Singh Ram Sampath full song' },
  { t: 'Tum Se', f: 'Teri Baaton Mein Aisa Uljha Jiya', y: 2024, q: 'Tum Se Teri Baaton Mein Aisa Uljha Jiya song' },
  { t: 'Akhiyaan Gulaab', f: 'Teri Baaton Mein Aisa Uljha Jiya', y: 2024 },
  { t: 'Pehle Bhi Main', f: 'Animal', y: 2023 },
  { t: 'Ae Watan', f: 'Raazi', y: 2018 },
  { t: 'Dilbaro Padhai', f: 'Raazi', y: 2018, q: 'Dilbaro Raazi Harshdeep Kaur Vibha Saraf full song' },
];
