// Qawwali Wala — dargah courtyard after Isha. Nusrat and the Sabri Brothers,
// the film qawwali tradition, Coke Studio, and the ghazal end of the night.

export default [
  { t: 'Dama Dam Mast Qalandar', a: 'Nusrat Fateh Ali Khan', q: 'Dam Mast Qalandar Mast Mast Nusrat Fateh Ali Khan qawwali' },
  { t: 'Tumhe Dillagi', a: 'Nusrat Fateh Ali Khan', q: 'Tumhe Dillagi Bhool Jani Padegi Nusrat Fateh Ali Khan original qawwali' },
  { t: 'Afreen Afreen', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Sanson Ki Mala Pe', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Bhar Do Jholi Meri', f: 'Bajrangi Bhaijaan', y: 2015 },
  { t: 'Kun Faya Kun', f: 'Rockstar', y: 2011 },
  { t: 'Khwaja Mere Khwaja', f: 'Jodhaa Akbar', y: 2008 },
  { t: 'Piya Haji Ali', f: 'Fiza', y: 2000, q: 'Piya Haji Ali full song Fiza A R Rahman Srinivas' },
  { t: 'Arziyan', f: 'Delhi-6', y: 2009 },
  { t: 'Parda Hai Parda', f: 'Amar Akbar Anthony', y: 1977 },
  { t: 'Hai Agar Dushman', f: 'Hum Kisise Kum Naheen', y: 1977 },
  { t: 'Tajdar-e-Haram', a: 'Atif Aslam', q: 'Tajdar-e-Haram Atif Aslam Coke Studio Season 8 Episode 1' },

  { t: 'Allah Hoo Allah Hoo', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Mera Piya Ghar Aaya', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Yeh Jo Halka Halka Suroor Hai', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Kinna Sohna Tainu Rab Ne Banaya', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Sochta Hoon Ke Woh Kitne Masoom The', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Halka Halka Suroor', a: 'Nusrat Fateh Ali Khan', q: 'Yeh Jo Halka Halka Suroor Hai Nusrat Fateh Ali Khan live' },
  { t: 'Akhiyan Udeek Diyan', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Tere Bin Nahi Lagda', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Sanu Ek Pal Chain', a: 'Nusrat Fateh Ali Khan', q: 'Sanu Ek Pal Chain Na Aave Nusrat Fateh Ali Khan original' },
  { t: 'Menu Ishq Da Lagya Rog', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Jhoole Jhoole Lal', a: 'Nusrat Fateh Ali Khan', q: 'Dama Dam Mast Qalandar Jhoole Lal Nusrat qawwali' },
  { t: 'Kise Da Yaar Na Vichhre', a: 'Nusrat Fateh Ali Khan' },
  { t: 'Ali Maula Ali Maula', a: 'Nusrat Fateh Ali Khan', q: 'Ali Maula Ali Dam Dam qawwali Nusrat' },
  { t: 'Bhar Do Jholi Sabri', a: 'Sabri Brothers', q: 'Bhar Do Jholi Meri Sabri Brothers original qawwali' },
  { t: 'Tajdar-e-Haram Sabri', a: 'Sabri Brothers', q: 'Tajdar-e-Haram Sabri Brothers original qawwali' },
  { t: 'Mera Koi Nahin Hai Tere Siwa', a: 'Sabri Brothers', q: 'Mera Koi Nahi Hai Tere Siwa qawwali Sabri' },
  { t: 'Savere Ka Sooraj', a: 'Sabri Brothers', q: 'Sabri Brothers famous qawwali live' },
  { t: 'Aaj Rang Hai', a: 'Amir Khusro', q: 'Aaj Rang Hai Ri Maa qawwali Amir Khusro' },
  { t: 'Chhap Tilak Sab Chheeni', a: 'Amir Khusro', q: 'Chhap Tilak Sab Cheeni qawwali Abida Parveen' },
  { t: 'Man Kunto Maula', q: 'Man Kunto Maula qawwali Amir Khusro' },
  { t: 'Rang Amir Khusro', q: 'Rang qawwali Amir Khusro Nizamuddin Auliya' },
  { t: 'Ye Naina Ye Kaajal', a: 'Abida Parveen', q: 'Tere Ishq Nachaya Abida Parveen sufi' },
  { t: 'Tere Ishq Nachaya', a: 'Abida Parveen' },
  { t: 'Yaar Ko Humne', a: 'Abida Parveen', q: 'Yaar Ko Humne Ja Ba Ja Dekha Abida Parveen' },
  { t: 'Aaqa', a: 'Abida Parveen', q: 'Abida Parveen sufi kalam live performance' },
  { t: 'Jab Se Tune Mujhe', a: 'Rahat Fateh Ali Khan', q: 'Jab Se Tune Mujhe Deewana Bana Rakha Hai qawwali' },
  { t: 'Sanson Ki Mala Rahat', a: 'Rahat Fateh Ali Khan', q: 'Sanson Ki Mala Pe Rahat Fateh Ali Khan sufi' },
  { t: 'Ya Ali Rahat', a: 'Rahat Fateh Ali Khan', q: 'Ya Ali Gangster Rahat Fateh Ali Khan full song' },
  { t: 'Zaroori Tha', a: 'Rahat Fateh Ali Khan', y: 2014 },
  { t: 'O Re Piya', f: 'Aaja Nachle', y: 2007 },
  { t: 'Naina Thag Lenge Qawwali', f: 'Omkara', y: 2006, q: 'Naina Thag Lenge Omkara Rahat Fateh Ali Khan full song' },
  { t: 'Mann Ki Lagan', f: 'Paap', y: 2003 },
  { t: 'Jiya Dhadak Dhadak', f: 'Kalyug', y: 2005 },
  { t: 'Tere Mast Mast Do Nain', f: 'Dabangg', y: 2010 },
  { t: 'Teri Meri Prem Kahani', f: 'Bodyguard', y: 2011 },
  { t: 'Ajab Si', f: 'Om Shanti Om', y: 2007 },
  { t: 'Dil To Bachcha Hai Ji', f: 'Ishqiya', y: 2010 },
  { t: 'Bin Tere', f: 'I Hate Luv Storys', y: 2010 },
  { t: 'Aaj Din Chadheya', f: 'Love Aaj Kal', y: 2009 },
  { t: 'Yeh Honsla', f: 'Dor', y: 2006 },
  { t: 'Maula Mere Maula', f: 'Anwar', y: 2007 },
  { t: 'Tose Naina Lage', f: 'Anwar', y: 2007 },
  { t: 'Kaisi Paheli Zindagani', f: 'Parineeta', y: 2005 },
  { t: 'Piyu Bole', f: 'Parineeta', y: 2005 },
  { t: 'Chhod Do Aanchal', f: 'Paying Guest', y: 1957 },
  { t: 'Nigahen Milane Ko Jee Chahta Hai', f: 'Dil Hi To Hai', y: 1963 },
  { t: 'Na To Karvan Ki Talash Hai', f: 'Barsaat Ki Raat', y: 1960 },
  { t: 'Yeh Ishq Ishq Hai', f: 'Barsaat Ki Raat', y: 1960 },
  { t: 'Zindagi Bhar Nahi Bhoolegi', f: 'Barsaat Ki Raat', y: 1960 },
  { t: 'Jaane Kaise Kab Kahan', f: 'Shakti', y: 1982 },
  { t: 'Hum Kisi Se Kum Nahin Qawwali', f: 'Hum Kisise Kum Naheen', y: 1977, q: 'Hai Agar Dushman Zamana Hum Kisise Kum Nahin qawwali' },
  { t: 'Shakal Pe Mat Ja', f: 'Hum Kisise Kum Naheen', y: 1977 },
  { t: 'Ishq Bina Kya Marna Yaara', f: 'Taal', y: 1999 },
  { t: 'Piya Haji Ali Fiza', f: 'Fiza', y: 2000, q: 'Piya Haji Ali qawwali Fiza Hrithik Roshan song' },
  { t: 'Mast Qalandar Coke Studio', a: 'Coke Studio', q: 'Lal Meri Pat Rakhio Coke Studio Pakistan' },
  { t: 'Aaj Jane Ki Zid Na Karo', a: 'Farida Khanum' },
  { t: 'Ranjish Hi Sahi', a: 'Mehdi Hassan' },
  { t: 'Patta Patta Boota Boota', a: 'Mehdi Hassan' },
  { t: 'Mujhe Tum Nazar Se', a: 'Mehdi Hassan' },
  { t: 'Gulon Mein Rang Bhare', a: 'Mehdi Hassan' },
  { t: 'Chupke Chupke Raat Din', a: 'Ghulam Ali' },
  { t: 'Hungama Hai Kyon Barpa', a: 'Ghulam Ali' },
  { t: 'Awargi', a: 'Ghulam Ali' },
  { t: 'Kal Chaudhvin Ki Raat Thi', a: 'Ghulam Ali' },
  { t: 'Dil Mein Ek Lehar', a: 'Ghulam Ali' },
  { t: 'Tum Itna Jo Muskura Rahe Ho Ghazal', a: 'Jagjit Singh', q: 'Tum Itna Jo Muskura Rahe Ho Jagjit Singh ghazal' },
  { t: 'Hothon Se Chhoo Lo Tum', a: 'Jagjit Singh' },
  { t: 'Tumko Dekha To Yeh Khayal Aaya', a: 'Jagjit Singh' },
  { t: 'Woh Kagaz Ki Kashti', a: 'Jagjit Singh' },
  { t: 'Sarakti Jaye Hai Rukh Se', a: 'Jagjit Singh' },
  { t: 'Koi Fariyaad', a: 'Jagjit Singh' },
  { t: 'Chithi Na Koi Sandesh Ghazal', a: 'Jagjit Singh', q: 'Chithi Na Koi Sandesh Jagjit Singh Dushman' },
  { t: 'Baat Niklegi To Phir', a: 'Jagjit Singh' },
  { t: 'Aahista Aahista', a: 'Jagjit Singh' },
  { t: 'Chandi Jaisa Rang', a: 'Pankaj Udhas' },
  { t: 'Aur Aahista Kijiye Baatein', a: 'Pankaj Udhas' },
  { t: 'Na Kajre Ki Dhar', a: 'Pankaj Udhas' },
  { t: 'Jiye To Jiye Kaise Ghazal', a: 'Pankaj Udhas', q: 'Deewaron Se Milkar Rona Pankaj Udhas ghazal' },
  { t: 'Ghungroo Toot Gaye Ghazal', a: 'Pankaj Udhas', q: 'Ghungroo Toot Gaye Pankaj Udhas ghazal' },
  { t: 'Thodi Thodi Piya Karo', a: 'Pankaj Udhas' },
  { t: 'Ek Taraf Uska Ghar', a: 'Pankaj Udhas' },
  { t: 'Aaine Ke Sau Tukde', a: 'Pankaj Udhas' },
  { t: 'Rafta Rafta Woh Meri', a: 'Mehdi Hassan' },
  { t: 'Zindagi Mein To Sabhi', a: 'Jagjit Singh' },
  { t: 'Jhuki Jhuki Si Nazar Ghazal', a: 'Jagjit Singh', q: 'Jhuki Jhuki Si Nazar Jagjit Singh Arth ghazal' },
  { t: 'Ahista Ahista Sufi', a: 'Sufi', q: 'Damadam Mast Qalandar Runa Laila qawwali' },
  { t: 'Chaap Tilak Coke Studio', a: 'Coke Studio', q: 'Chhaap Tilak Abida Parveen Rahat Coke Studio' },
  { t: 'Aaya Tere Dar Par', f: 'Veer-Zaara', y: 2004 },
  { t: 'Main Yahaan Hoon', f: 'Veer-Zaara', y: 2004 },
  { t: 'Tere Liye', f: 'Veer-Zaara', y: 2004 },
  { t: 'Do Pal', f: 'Veer-Zaara', y: 2004 },
];
