// Saloon Wala — 90s Hindi film hits, the ones that actually played on the
// barbershop radio. Mass-market, chart-topping, everybody-knows-the-chorus.

export default [
  { t: 'Tu Cheez Badi Hai Mast Mast', f: 'Mohra', y: 1994 },
  { t: 'Ole Ole', f: 'Yeh Dillagi', y: 1994 },
  { t: 'Yeh Kaali Kaali Aankhen', f: 'Baazigar', y: 1993 },
  { t: 'Sona Kitna Sona Hai', f: 'Hero No. 1', y: 1997 },
  { t: 'Churake Dil Mera', f: 'Main Khiladi Tu Anari', y: 1994, q: 'Chura Ke Dil Mera 4K video song Main Khiladi Tu Anari Akshay Shilpa' },
  { t: 'Akhiyon Se Goli Maare', f: 'Dulhe Raja', y: 1998, q: 'Akhiyon Se Goli Maare full video song Dulhe Raja Govinda Raveena' },
  { t: 'Ruk Ruk Ruk', f: 'Vijaypath', y: 1994 },
  { t: 'Jhanjhariya', f: 'Krishna', y: 1996 },
  { t: 'Dhak Dhak Karne Laga', f: 'Beta', y: 1992 },
  { t: 'Pehla Nasha', f: 'Jo Jeeta Wohi Sikandar', y: 1992 },
  { t: 'Kisi Disco Mein Jaaye', f: 'Bade Miyan Chote Miyan', y: 1998 },
  { t: 'Tumse Milne Ki Tamanna Hai', f: 'Saajan', y: 1991 },

  { t: 'Saat Samundar Paar', f: 'Vishwatma', y: 1992 },
  { t: 'Baazigar O Baazigar', f: 'Baazigar', y: 1993 },
  { t: 'Kitaben Bahut Si', f: 'Baazigar', y: 1993 },
  { t: 'Chhupana Bhi Nahi Aata', f: 'Baazigar', y: 1993 },
  { t: 'Jaadu Teri Nazar', f: 'Darr', y: 1993 },
  { t: 'Tu Mere Samne', f: 'Darr', y: 1993 },
  { t: 'Ang Se Ang Lagana', f: 'Darr', y: 1993 },
  { t: 'Ghungat Ki Aad Se', f: 'Hum Hain Rahi Pyar Ke', y: 1993 },
  { t: 'Julie Julie', f: 'Hum Hain Rahi Pyar Ke', y: 1993 },
  { t: 'Ek Ladki Ko Dekha', f: '1942: A Love Story', y: 1994 },
  { t: 'Kuch Na Kaho', f: '1942: A Love Story', y: 1994 },
  { t: 'Rim Jhim Rim Jhim', f: '1942: A Love Story', y: 1994 },
  { t: 'Dil Hai Ke Manta Nahin', f: 'Dil Hai Ke Manta Nahin', y: 1991 },
  { t: 'Tu Pyar Hai Kisi Aur Ka', f: 'Dil Hai Ke Manta Nahin', y: 1991 },
  { t: 'Nazar Ke Samne', f: 'Aashiqui', y: 1990 },
  { t: 'Dheere Dheere Se', f: 'Aashiqui', y: 1990 },
  { t: 'Ab Tere Bin Jee Lenge Hum', f: 'Aashiqui', y: 1990 },
  { t: 'Jaane Jigar Jaaneman', f: 'Aashiqui', y: 1990 },
  { t: 'Teri Umeed Tera Intezar', f: 'Deewana', y: 1992 },
  { t: 'Aisi Deewangi', f: 'Deewana', y: 1992 },
  { t: 'Payaliya', f: 'Deewana', y: 1992 },
  { t: 'Koi Na Koi Chahiye', f: 'Deewana', y: 1992 },
  { t: 'Bahut Pyar Karte Hain', f: 'Saajan', y: 1991 },
  { t: 'Dekha Hai Pehli Baar', f: 'Saajan', y: 1991 },
  { t: 'Mera Dil Bhi Kitna Pagal Hai', f: 'Saajan', y: 1991 },
  { t: 'Jeeye To Jeeye Kaise', f: 'Saajan', y: 1991 },
  { t: 'Koyal Si Teri Boli', f: 'Beta', y: 1992 },
  { t: 'Aisa Zakhm Diya Hai', f: 'Akele Hum Akele Tum', y: 1995 },
  { t: 'Dil Mera Churaya Kyun', f: 'Akele Hum Akele Tum', y: 1995 },
  { t: 'Raja Ko Rani Se Pyar Ho Gaya', f: 'Akele Hum Akele Tum', y: 1995 },
  { t: 'Mere Khwabon Mein', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
  { t: 'Ho Gaya Hai Tujhko To Pyar Sajna', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
  { t: 'Ruk Ja O Dil Deewane', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
  { t: 'Zara Sa Jhoom Loon Main', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
  { t: 'Koi Mil Gaya', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Kuch Kuch Hota Hai', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Ladki Badi Anjani Hai', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Yeh Ladka Hai Allah', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Tujhe Yaad Na Meri Aayi', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Jaati Hoon Main', f: 'Karan Arjun', y: 1995 },
  { t: 'Yeh Bandhan To Pyar Ka Bandhan Hai', f: 'Karan Arjun', y: 1995 },
  { t: 'Bhangda Paale', f: 'Karan Arjun', y: 1995 },
  { t: 'Chaand Taare', f: 'Yes Boss', y: 1997 },
  { t: 'Main Koi Aisa Geet Gaoon', f: 'Yes Boss', y: 1997 },
  { t: 'Ek Din Aap Yun Humko Mil Jayenge', f: 'Yes Boss', y: 1997 },
  { t: 'Aaye Ho Meri Zindagi Mein', f: 'Raja Hindustani', y: 1996 },
  { t: 'Kitna Pyara Tujhe Rab Ne Banaya', f: 'Raja Hindustani', y: 1996 },
  { t: 'Tere Ishq Mein Naachenge', f: 'Raja Hindustani', y: 1996 },
  { t: 'Neend Churayi Meri', f: 'Ishq', y: 1997 },
  { t: 'Dekho Dekho Jaanam', f: 'Ishq', y: 1997 },
  { t: 'Humko Tumse Pyaar Hai', f: 'Ishq', y: 1997 },
  { t: 'Chori Chori Sapno Mein', f: 'Barsaat', y: 1995 },
  { t: 'Dil Deewana Bin Sajna Ke', f: 'Maine Pyar Kiya', y: 1989 },
  { t: 'Aate Jaate Hanste Gaate', f: 'Maine Pyar Kiya', y: 1989 },
  { t: 'Kabootar Ja Ja Ja', f: 'Maine Pyar Kiya', y: 1989 },
  { t: 'Mere Rang Mein Rangne Wali', f: 'Maine Pyar Kiya', y: 1989 },
  { t: 'Pehla Pehla Pyar Hai', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Maye Ni Maye', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Chocolate Lime Juice', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Sona Sona', f: 'Major Saab', y: 1998 },
  { t: 'Akhiyan Milaoon Kabhi', f: 'Raja', y: 1995 },
  { t: 'Nazrein Mili Dil Dhadka', f: 'Raja', y: 1995 },
  { t: 'Sarkai Lo Khatiya', f: 'Raja Babu', y: 1994 },
  { t: 'A Ah Aa E Ee', f: 'Raja Babu', y: 1994 },
  { t: 'Gore Gore Mukhde Pe', f: 'Suhaag', y: 1994 },
  { t: 'Ek Pal Ka Jeena', f: 'Kaho Naa... Pyaar Hai', y: 2000 },
  { t: 'Na Tum Jaano Na Hum', f: 'Kaho Naa... Pyaar Hai', y: 2000 },
  { t: 'Pyaar Ki Kashti Mein', f: 'Kaho Naa... Pyaar Hai', y: 2000 },
  { t: 'Dil Ne Yeh Kaha Hai Dil Se', f: 'Dhadkan', y: 2000 },
  { t: 'Tum Dil Ki Dhadkan Mein', f: 'Dhadkan', y: 2000 },
  { t: 'Taal Se Taal Mila', f: 'Taal', y: 1999 },
  { t: 'Ishq Bina', f: 'Taal', y: 1999 },
  { t: 'Ramta Jogi', f: 'Taal', y: 1999 },
  { t: 'Kariye Na', f: 'Taal', y: 1999 },
  { t: 'Aankhon Ki Gustakhiyan', f: 'Hum Dil De Chuke Sanam', y: 1999 },
  { t: 'Chand Chhupa Badal Mein', f: 'Hum Dil De Chuke Sanam', y: 1999 },
  { t: 'Nimbooda', f: 'Hum Dil De Chuke Sanam', y: 1999 },
  { t: 'Albela Sajan', f: 'Hum Dil De Chuke Sanam', y: 1999 },
  { t: 'Chhod Aaye Hum Woh Gali', f: 'Maachis', y: 1996 },
  { t: 'Chappa Chappa Charkha Chale', f: 'Maachis', y: 1996 },
  { t: 'Ghar Se Nikalte Hi', f: 'Papa Kehte Hain', y: 1996 },
  { t: 'Aankhon Mein Base Ho Tum', f: 'Takkar', y: 1995 },
  { t: 'Jaanam Samjha Karo', a: 'Asha Bhosle', y: 1997 },
  { t: 'Mehboob Mere', f: 'Fiza', y: 2000 },
  { t: 'Kaho Naa Pyaar Hai', f: 'Kaho Naa... Pyaar Hai', y: 2000 },
  { t: 'Suraj Hua Maddham', f: 'Kabhi Khushi Kabhie Gham', y: 2001 },
  { t: 'You Are My Sonia', f: 'Kabhi Khushi Kabhie Gham', y: 2001 },
  { t: 'Kya Kehna', f: 'Kya Kehna', y: 2000 },
  { t: 'Sona Nahi Na Sahi', f: 'Zubeidaa', y: 2001 },
  { t: 'Meri Chhoti Si Behen', f: 'Sirf Tum', y: 1999 },
  { t: 'Pyaar Ko Ho Jaane Do', f: 'Sirf Tum', y: 1999 },
];
