// Shaadi Wala — sangeet, baraat, vidaai and every uncle on the floor. Dhol,
// shehnai and the songs the DJ is contractually obliged to play.

export default [
  { t: 'Didi Tera Devar Deewana', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Mehndi Laga Ke Rakhna', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
  { t: 'Bole Chudiyan', f: 'Kabhi Khushi Kabhie Gham', y: 2001 },
  { t: 'Aaj Mere Yaar Ki Shaadi Hai', f: 'Aadmi Sadak Ka', y: 1977 },
  { t: 'London Thumakda', f: 'Queen', y: 2014 },
  { t: 'Nagada Sang Dhol', f: 'Goliyon Ki Raasleela Ram-Leela', y: 2013 },
  { t: 'Gallan Goodiyaan', f: 'Dil Dhadakne Do', y: 2015 },
  { t: 'Saajanji Ghar Aaye', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Dulhe Ka Sehra', f: 'Dhadkan', y: 2000 },
  { t: 'Chunari Chunari', f: 'Biwi No.1', y: 1999 },
  { t: 'Kajra Re', f: 'Bunty Aur Babli', y: 2005 },
  { t: 'Wah Wah Ramji', f: 'Hum Aapke Hain Koun..!', y: 1994 },

  { t: 'Joote Do Paise Lo', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Lo Chali Main', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Dhiktana', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Mausam Ka Jaadu', f: 'Hum Aapke Hain Koun..!', y: 1994 },
  { t: 'Bahon Ke Darmiyan', f: 'Khamoshi: The Musical', y: 1996 },
  { t: 'Shava Shava', f: 'Kabhi Khushi Kabhie Gham', y: 2001 },
  { t: 'Yeh Ladka Hai Deewana', f: 'Kuch Kuch Hota Hai', y: 1998 },
  { t: 'Mahi Ve', f: 'Kal Ho Naa Ho', y: 2003 },
  { t: 'It’s The Time To Disco', f: 'Kal Ho Naa Ho', y: 2003 },
  { t: 'Pretty Woman', f: 'Kal Ho Naa Ho', y: 2003 },
  { t: 'Kal Ho Naa Ho', f: 'Kal Ho Naa Ho', y: 2003 },
  { t: 'Desi Girl', f: 'Dostana', y: 2008 },
  { t: 'Shut Up And Bounce', f: 'Dostana', y: 2008 },
  { t: 'Aaj Ki Party', f: 'Bajrangi Bhaijaan', y: 2015 },
  { t: 'Tune Maari Entriyaan Shaadi', f: 'Gunday', y: 2014, q: 'Tune Maari Entriyaan Gunday full video song' },
  { t: 'Dholi Taro Dhol Baaje', f: 'Hum Dil De Chuke Sanam', y: 1999 },
  { t: 'Ang Laga De', f: 'Goliyon Ki Raasleela Ram-Leela', y: 2013 },
  { t: 'Lahu Munh Lag Gaya', f: 'Goliyon Ki Raasleela Ram-Leela', y: 2013 },
  { t: 'Tattad Tattad', f: 'Goliyon Ki Raasleela Ram-Leela', y: 2013 },
  { t: 'Ram Chahe Leela', f: 'Goliyon Ki Raasleela Ram-Leela', y: 2013 },
  { t: 'Pinga', f: 'Bajirao Mastani', y: 2015 },
  { t: 'Deewani Mastani', f: 'Bajirao Mastani', y: 2015 },
  { t: 'Malhari', f: 'Bajirao Mastani', y: 2015 },
  { t: 'Ghoomar', f: 'Padmaavat', y: 2018 },
  { t: 'Nainowale Ne', f: 'Padmaavat', y: 2018 },
  { t: 'Sanu Ek Pal Chain', f: 'Raid', y: 2018 },
  { t: 'First Class', f: 'Kalank', y: 2019 },
  { t: 'Tabaah Ho Gaye', f: 'Kalank', y: 2019 },
  { t: 'Aira Gaira', f: 'Kalank', y: 2019 },
  { t: 'Nachde Ne Saare Baar Baar', f: 'Baar Baar Dekho', y: 2016, q: 'Nachde Ne Saare Baar Baar Dekho Jasleen Royal full song' },
  { t: 'Sweety Tera Drama', f: 'Bareilly Ki Barfi', y: 2017 },
  { t: 'Aankh Marey Shaadi', f: 'Simmba', y: 2018, q: 'Aankh Marey Simmba full video song Neha Kakkar' },
  { t: 'Bum Diggy Diggy', f: 'Sonu Ke Titu Ki Sweety', y: 2018 },
  { t: 'Dil Chori', f: 'Sonu Ke Titu Ki Sweety', y: 2018 },
  { t: 'Chhote Chhote Peg', f: 'Sonu Ke Titu Ki Sweety', y: 2018 },
  { t: 'Subah Subah', f: 'Sonu Ke Titu Ki Sweety', y: 2018 },
  { t: 'Kala Chashma Shaadi', f: 'Baar Baar Dekho', y: 2016, q: 'Kala Chashma Baar Baar Dekho Neha Kakkar Badshah' },
  { t: 'Gud Naal Ishq Mitha Shaadi', a: 'Malkit Singh', q: 'Gur Nalo Ishq Mitha Malkit Singh original bhangra' },
  { t: 'Balle Balle', f: 'Bride And Prejudice', y: 2004, q: 'Balle Balle Bride and Prejudice song' },
  { t: 'Mundeya To Bach Ke Rahi', a: 'Labh Janjua', q: 'Mundeya To Bach Ke Rahi punjabi wedding song' },
  { t: 'Bhangra Paa Le', f: 'Bhangra Paa Le', y: 2020 },
  { t: 'Kudi Nu Nachne De', f: 'Angrezi Medium', y: 2020 },
  { t: 'Laung Laachi', a: 'Mannat Noor', y: 2018 },
  { t: 'Nikle Currant', a: 'Jassi Gill', y: 2018 },
  { t: 'Gud Naal Ishq Mitha Honey', a: 'Yo Yo Honey Singh', y: 2019, q: 'Gur Nalo Ishq Mitha Honey Singh remake full song' },
  { t: 'Dilbaro', f: 'Raazi', y: 2018 },
  { t: 'Din Shagna Da', f: 'Phillauri', y: 2017 },
  { t: 'Sahiba', f: 'Phillauri', y: 2017 },
  { t: 'Naah', a: 'Harrdy Sandhu', y: 2017 },
  { t: 'Backbone', a: 'Harrdy Sandhu', y: 2017 },
  { t: 'Soch', a: 'Harrdy Sandhu', y: 2013 },
  { t: 'Bijlee Bijlee', a: 'Harrdy Sandhu', y: 2021 },
  { t: 'Kudiye Ni Teri', a: 'Aparshakti Khurana', q: 'Kudiye Ni Teri Vaari Vaari song' },
  { t: 'Genda Phool Shaadi', a: 'Badshah', y: 2020, q: 'Genda Phool Badshah Payal Dev full song' },
  { t: 'Paagal', a: 'Badshah', y: 2019 },
  { t: 'Jugnu', a: 'Badshah', y: 2021 },
  { t: 'DJ Waley Babu', a: 'Badshah', y: 2015 },
  { t: 'Abhi Toh Party', f: 'Khoobsurat', y: 2014, q: 'Abhi Toh Party Shuru Hui Hai Khoobsurat Badshah full video' },
  { t: 'Saree Ke Fall Sa Shaadi', f: 'R... Rajkumar', y: 2013, q: 'Saree Ke Fall Sa R Rajkumar full video song' },
  { t: 'Radha Nachegi', f: 'Tevar', y: 2015 },
  { t: 'Superman', f: 'Tevar', y: 2015 },
  { t: 'Prem Ratan Dhan Payo', f: 'Prem Ratan Dhan Payo', y: 2015 },
  { t: 'Jab Tum Chaho', f: 'Prem Ratan Dhan Payo', y: 2015 },
  { t: 'Aaj Unse Milna Hai', f: 'Prem Ratan Dhan Payo', y: 2015 },
  { t: 'Bajrangi Bhaijaan Selfie', f: 'Bajrangi Bhaijaan', y: 2015, q: 'Selfie Le Le Re Bajrangi Bhaijaan full video song' },
  { t: 'Baby Ko Bass', f: 'Sultan', y: 2016, q: 'Baby Ko Bass Pasand Hai Sultan full video song' },
  { t: 'Photocopy Maar Li', f: 'Jai Ho', y: 2014, q: 'Photocopy Jai Ho Salman Khan full song' },
  { t: 'Nachan Farrate', f: 'All Is Well', y: 2015 },
  { t: 'Kar Gayi Chull Shaadi', f: 'Kapoor & Sons', y: 2016, q: 'Kar Gayi Chull Kapoor and Sons full video song' },
  { t: 'Cutiepie Shaadi', f: 'Ae Dil Hai Mushkil', y: 2016, q: 'Cutiepie Ae Dil Hai Mushkil full video song' },
  { t: 'Ghungroo Toot Gaye', f: 'War', y: 2019, q: 'Ghungroo War Hrithik Roshan Vaani Kapoor full song' },
  { t: 'Dance Ka Bhoot', f: 'Brahmastra', y: 2022 },
  { t: 'Jhoome Jo Pathaan Shaadi', f: 'Pathaan', y: 2023, q: 'Jhoome Jo Pathaan full song Arijit Singh Sukriti' },
  { t: 'What Jhumka', f: 'Rocky Aur Rani Kii Prem Kahaani', y: 2023 },
  { t: 'Tum Kya Mile', f: 'Rocky Aur Rani Kii Prem Kahaani', y: 2023 },
  { t: 'Dhindhora Baje Re', f: 'Rocky Aur Rani Kii Prem Kahaani', y: 2023 },
  { t: 'Ve Kamleya', f: 'Rocky Aur Rani Kii Prem Kahaani', y: 2023 },
  { t: 'Sajni', f: 'Laapataa Ladies', y: 2024 },
  { t: 'Ghar More Pardesiya Shaadi', f: 'Kalank', y: 2019, q: 'Ghar More Pardesiya Kalank Shreya Ghoshal full video' },
  { t: 'Mere Yaar Ki Shaadi Hai', f: 'Mere Yaar Ki Shaadi Hai', y: 2002 },
  { t: 'Sharara Sharara', f: 'Mere Yaar Ki Shaadi Hai', y: 2002 },
  { t: 'Aaja Nachle', f: 'Aaja Nachle', y: 2007 },
  { t: 'Show Me Your Jalwa', f: 'Aaja Nachle', y: 2007 },
  { t: 'Ishq Hua', f: 'Aaja Nachle', y: 2007 },
  { t: 'Salaam-e-Ishq', f: 'Salaam-e-Ishq', y: 2007 },
  { t: 'Piya Piya O Piya', f: 'Har Dil Jo Pyar Karega', y: 2000 },
];
