// Train Wala — sleeper class, shutter up, 3am. Kishore-heavy retro, the great
// R.D. Burman nights, and everything that sounds like fields going past.

export default [
  { t: 'Chaiyya Chaiyya', f: 'Dil Se..', y: 1998 },
  { t: 'Mere Sapno Ki Rani', f: 'Aradhana', y: 1969, q: 'Mere Sapno Ki Rani Aradhana Kishore Kumar Rajesh Khanna original song' },
  { t: 'Gaadi Bula Rahi Hai', f: 'Dost', y: 1974 },
  { t: 'Zindagi Ka Safar', f: 'Safar', y: 1970 },
  { t: 'Kuch To Log Kahenge', f: 'Amar Prem', y: 1972 },
  { t: 'Chingari Koi Bhadke', f: 'Amar Prem', y: 1972 },
  { t: 'Yeh Shaam Mastani', f: 'Kati Patang', y: 1970 },
  { t: 'Diye Jalte Hain', f: 'Namak Haraam', y: 1973 },
  { t: 'Main Shayar Badnaam', f: 'Namak Haraam', y: 1973 },
  { t: 'O Mere Dil Ke Chain', f: 'Mere Jeevan Saathi', y: 1972 },
  { t: 'Raat Kali Ek Khwab Mein Aayi', f: 'Buddha Mil Gaya', y: 1971 },
  { t: 'Rail Gaadi', a: 'Ashok Kumar', q: 'Rail Gaadi Ashok Kumar song' },

  { t: 'Roop Tera Mastana', f: 'Aradhana', y: 1969 },
  { t: 'Kora Kagaz Tha Ye Man Mera', f: 'Aradhana', y: 1969 },
  { t: 'Gunguna Rahe Hain Bhanwre', f: 'Aradhana', y: 1969 },
  { t: 'Baghon Mein Bahar Hai', f: 'Aradhana', y: 1969 },
  { t: 'Yeh Jo Mohabbat Hai', f: 'Kati Patang', y: 1970 },
  { t: 'Pyar Diwana Hota Hai', f: 'Kati Patang', y: 1970 },
  { t: 'Jis Gali Mein Tera Ghar', f: 'Kati Patang', y: 1970 },
  { t: 'Na Koi Umang Hai', f: 'Kati Patang', y: 1970 },
  { t: 'Chala Jata Hoon Kisi Ki Dhun Mein', f: 'Mere Jeevan Saathi', y: 1972 },
  { t: 'Deewana Leke Aaya Hai', f: 'Mere Jeevan Saathi', y: 1972 },
  { t: 'Bade Achhe Lagte Hain Train', f: 'Balika Badhu', y: 1976, q: 'Bade Achhe Lagte Hain Balika Badhu Amit Kumar original' },
  { t: 'Zindagi Ek Safar Train', f: 'Andaz', y: 1971, q: 'Zindagi Ek Safar Hai Suhana Andaz Kishore Kumar full song' },
  { t: 'Rim Jhim Gire Sawan Train', f: 'Manzil', y: 1979, q: 'Rimjhim Gire Sawan Manzil Kishore Kumar male version' },
  { t: 'O Manjhi Re', f: 'Khushboo', y: 1975 },
  { t: 'Do Naina Ek Kahani', f: 'Masoom', y: 1983 },
  { t: 'Tujhse Naraz Nahi Zindagi', f: 'Masoom', y: 1983 },
  { t: 'Lakdi Ki Kathi', f: 'Masoom', y: 1983 },
  { t: 'Huzoor Is Kadar', f: 'Masoom', y: 1983 },
  { t: 'Musafir Hoon Yaaron Train', f: 'Parichay', y: 1972, q: 'Musafir Hoon Yaaron Parichay Kishore Kumar full song' },
  { t: 'Beeti Na Bitai Raina', f: 'Parichay', y: 1972 },
  { t: 'Sa Re Ke Sa Re', f: 'Parichay', y: 1972 },
  { t: 'Mere Naina Sawan Bhadon Train', f: 'Mehbooba', y: 1976, q: 'Mere Naina Sawan Bhadon Mehbooba Kishore Kumar' },
  { t: 'Aap Ki Ankhon Mein Kuch', f: 'Ghar', y: 1978 },
  { t: 'Tere Bina Jiya Jaye Na Train', f: 'Ghar', y: 1978, q: 'Tere Bina Jiya Jaye Na Ghar Lata Mangeshkar full song' },
  { t: 'Phir Wohi Raat Hai Train', f: 'Ghar', y: 1978, q: 'Phir Wahi Raat Hai Ghar Kishore Kumar full song' },
  { t: 'Aanewala Pal Jaanewala Hai', f: 'Golmaal', y: 1979 },
  { t: 'Golmaal Hai Bhai Sab Golmaal Hai', f: 'Golmaal', y: 1979 },
  { t: 'Ek Din Bik Jayega Train', f: 'Dharam Karam', y: 1975, q: 'Ek Din Bik Jayega Mukesh Dharam Karam full song' },
  { t: 'O Hansini', f: 'Zehreela Insaan', y: 1974 },
  { t: 'Yeh Lal Rang', f: 'Prem Nagar', y: 1974 },
  { t: 'Dilbar Mere Kab Tak Mujhe', f: 'Satte Pe Satta', y: 1982 },
  { t: 'Pyar Humein Kis Mod Pe', f: 'Satte Pe Satta', y: 1982 },
  { t: 'Zindagi Milke Bitayenge', f: 'Satte Pe Satta', y: 1982 },
  { t: 'Aap Ke Anurodh Pe Train', f: 'Anurodh', y: 1977, q: 'Aap Ke Anurodh Pe Kishore Kumar full song' },
  { t: 'Mere Dil Mein Aaj Kya Hai', f: 'Daag', y: 1973 },
  { t: 'Ab Chahe Maa Roothe', f: 'Daag', y: 1973 },
  { t: 'Ni Sultana Re', f: 'Pyar Ka Mausam', y: 1969 },
  { t: 'Tum Bin Jaoon Kahan', f: 'Pyar Ka Mausam', y: 1969 },
  { t: 'Yeh Sham Mastani Train', f: 'Kati Patang', y: 1970, q: 'Yeh Shaam Mastani Kati Patang Kishore Kumar original' },
  { t: 'Meri Bheegi Bheegi Si', f: 'Anamika', y: 1973 },
  { t: 'Jaane Jaan Dhoondta', f: 'Jawani Diwani', y: 1972 },
  { t: 'Aage Bhi Jaane Na Tu', f: 'Waqt', y: 1965 },
  { t: 'Ae Meri Zohra Jabeen', f: 'Waqt', y: 1965 },
  { t: 'Din Hai Bahar Ke', f: 'Waqt', y: 1965 },
  { t: 'Likhe Jo Khat Tujhe', f: 'Kanyadaan', y: 1968 },
  { t: 'Baar Baar Din Ye Aaye', f: 'Farz', y: 1967 },
  { t: 'Mast Baharon Ka Main Aashiq', f: 'Farz', y: 1967 },
  { t: 'Ek Ajnabee Haseena Se', f: 'Ajnabee', y: 1974 },
  { t: 'Hum Dono Do Premi', f: 'Ajnabee', y: 1974 },
  { t: 'Chalte Chalte Yunhi Koi', f: 'Pakeezah', y: 1972 },
  { t: 'Inhi Logon Ne', f: 'Pakeezah', y: 1972 },
  { t: 'Thare Rahiyo', f: 'Pakeezah', y: 1972 },
  { t: 'Mausam Hai Aashiqana', f: 'Pakeezah', y: 1972 },
  { t: 'Aaj Sajan Mohe Ang Laga Lo', f: 'Pyaasa', y: 1957 },
  { t: 'Hum Aapki Aankhon Mein', f: 'Pyaasa', y: 1957 },
  { t: 'Chaudhvin Ka Chand Ho', f: 'Chaudhvin Ka Chand', y: 1960 },
  { t: 'Na Jao Saiyaan', f: 'Sahib Bibi Aur Ghulam', y: 1962 },
  { t: 'Piya Aiso Jiya Mein', f: 'Sahib Bibi Aur Ghulam', y: 1962 },
  { t: 'Bhanwra Bada Nadaan Hai', f: 'Sahib Bibi Aur Ghulam', y: 1962 },
  { t: 'Lag Ja Gale', f: 'Woh Kaun Thi', y: 1964 },
  { t: 'Naina Barse Rimjhim', f: 'Woh Kaun Thi', y: 1964 },
  { t: 'Aap Yun Faaslon Se', f: 'Shankar Hussain', y: 1977 },
  { t: 'Yeh Nayan Dare Dare', f: 'Kohraa', y: 1964 },
  { t: 'Kahin Deep Jale Kahin Dil', f: 'Bees Saal Baad', y: 1962 },
  { t: 'Kahin Door Jab Din Train', f: 'Anand', y: 1971, q: 'Kahin Door Jab Din Dhal Jaye Anand Mukesh full song' },
  { t: 'Zindagi Kaisi Hai Paheli Train', f: 'Anand', y: 1971, q: 'Zindagi Kaisi Hai Paheli Anand Manna Dey full song' },
  { t: 'Na Jiya Lage Na', f: 'Anand', y: 1971 },
  { t: 'Chal Kahin Door Nikal Jayein', f: 'Doosra Aadmi', y: 1977 },
  { t: 'Kya Hua Tera Wada Train', f: 'Hum Kisise Kum Naheen', y: 1977, q: 'Kya Hua Tera Wada Mohammed Rafi full song' },
  { t: 'Tere Bina Zindagi Se Train', f: 'Aandhi', y: 1975, q: 'Tere Bina Zindagi Se Koi Aandhi Kishore Lata full song' },
  { t: 'Mera Kuch Saaman', f: 'Ijaazat', y: 1987 },
  { t: 'Katra Katra', f: 'Ijaazat', y: 1987 },
  { t: 'Khali Haath Shaam Aayi Hai', f: 'Ijaazat', y: 1987 },
  { t: 'Chhoti Si Kahani Se', f: 'Ijaazat', y: 1987 },
  { t: 'Roz Roz Aankhon Tale', f: 'Jeeva', y: 1986 },
  { t: 'Kya Yahi Pyar Hai', f: 'Rocky', y: 1981 },
  { t: 'Aa Dekhen Zara', f: 'Rocky', y: 1981 },
  { t: 'Hum Tum Ek Kamre Mein', f: 'Bobby', y: 1973 },
  { t: 'Jhoot Bole Kauwa Kaate', f: 'Bobby', y: 1973 },
  { t: 'Main Shayar To Nahin', f: 'Bobby', y: 1973 },
  { t: 'Na Chahoon Sona Chandi', f: 'Bobby', y: 1973 },
  { t: 'Dafliwale Dafli Baja', f: 'Sargam', y: 1979 },
  { t: 'Parbat Ke Peechhe', f: 'Mera Gaon Mera Desh', y: 1971 },
  { t: 'Aaja Aaja Main Hoon', f: 'Teesri Manzil', y: 1966, q: 'Aaja Aaja Main Hoon Pyar Tera Teesri Manzil Rafi' },
  { t: 'Gulabi Aankhen', f: 'The Train', y: 1970 },
  { t: 'Kis Liye Maine Pyar Kiya', f: 'The Train', y: 1970 },
  { t: 'Meri Jaan Maine Kaha', f: 'The Train', y: 1970 },
];
