// Truck Wala — the cabin canon. Separation, distance, letters from home, and
// the long dark stretch of national highway at 2am.

export default [
  { t: 'Chitthi Aayi Hai', f: 'Naam', y: 1986 },
  { t: 'Main Nikla Gaddi Leke', f: 'Gadar: Ek Prem Katha', y: 2001, q: 'Main Nikla Gaddi Leke Gadar 2001 Udit Narayan Sunny Deol full song' },
  { t: 'Pardesi Pardesi Jaana Nahin', f: 'Raja Hindustani', y: 1996 },
  { t: 'Tujhe Dekha To Ye Jaana Sanam', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
  { t: 'Chalte Chalte Mere Yeh Geet', f: 'Chalte Chalte', y: 1976 },
  { t: 'Ae Kaash Ke Hum', f: 'Kabhi Haan Kabhi Naa', y: 1994 },
  { t: 'Kya Hua Tera Wada', f: 'Hum Kisise Kum Naheen', y: 1977 },
  { t: 'Sochenge Tumhe Pyar', f: 'Deewana', y: 1992 },
  { t: 'Tadap Tadap Ke', f: 'Hum Dil De Chuke Sanam', y: 1999 },
  { t: 'Meri Mehbooba', f: 'Pardes', y: 1997 },
  { t: 'Dil Hoom Hoom Kare', f: 'Rudaali', y: 1993, q: 'Dil Hoom Hoom Kare Rudaali Lata Mangeshkar Bhupen Hazarika' },
  { t: 'Lambi Judai', f: 'Hero', y: 1983 },

  { t: 'Tere Bina Zindagi Se Koi', f: 'Aandhi', y: 1975 },
  { t: 'Tum Aa Gaye Ho Noor Aa Gaya', f: 'Aandhi', y: 1975 },
  { t: 'Zindagi Ke Safar Mein', f: 'Aap Ki Kasam', y: 1974 },
  { t: 'Karvaten Badalte Rahe', f: 'Aap Ki Kasam', y: 1974 },
  { t: 'Chhookar Mere Man Ko', f: 'Yaarana', y: 1981 },
  { t: 'Tere Chehre Se Nazar Nahin', f: 'Kabhi Kabhie', y: 1976 },
  { t: 'Kabhi Kabhie Mere Dil Mein', f: 'Kabhi Kabhie', y: 1976 },
  { t: 'Main Pal Do Pal Ka Shayar', f: 'Kabhi Kabhie', y: 1976 },
  { t: 'Dost Dost Na Raha', f: 'Sangam', y: 1964 },
  { t: 'Yeh Mera Prem Patra', f: 'Sangam', y: 1964 },
  { t: 'Mere Mehboob Qayamat Hogi', f: 'Mr. X In Bombay', y: 1964 },
  { t: 'Chal Akela Chal Akela', f: 'Sambandh', y: 1969 },
  { t: 'Jaane Woh Kaise Log The', f: 'Pyaasa', y: 1957 },
  { t: 'Yeh Duniya Agar Mil Bhi Jaye', f: 'Pyaasa', y: 1957 },
  { t: 'Waqt Ne Kiya Kya Haseen Sitam', f: 'Kaagaz Ke Phool', y: 1959 },
  { t: 'Hum Bekhudi Mein Tumko', f: 'Kala Pani', y: 1958 },
  { t: 'Din Dhal Jaye Haye', f: 'Guide', y: 1965 },
  { t: 'Tere Mere Sapne', f: 'Guide', y: 1965 },
  { t: 'Kya Se Kya Ho Gaya', f: 'Guide', y: 1965 },
  { t: 'Aaj Phir Jeene Ki Tamanna Hai', f: 'Guide', y: 1965 },
  { t: 'O Saathi Re', f: 'Muqaddar Ka Sikandar', y: 1978 },
  { t: 'Rote Hue Aate Hain Sab', f: 'Muqaddar Ka Sikandar', y: 1978 },
  { t: 'Dil Ke Tukde Tukde Karke', f: 'Dada', y: 1979 },
  { t: 'Ae Zindagi Gale Laga Le', f: 'Sadma', y: 1983 },
  { t: 'Surmayi Ankhiyon Mein', f: 'Sadma', y: 1983 },
  { t: 'Manzilein Apni Jagah Hain', f: 'Sharaabi', y: 1984 },
  { t: 'Inteha Ho Gayi Intezar Ki', f: 'Sharaabi', y: 1984 },
  { t: 'Mujhe Naulakha Manga De', f: 'Sharaabi', y: 1984 },
  { t: 'Chithi Na Koi Sandes', f: 'Dushman', y: 1998 },
  { t: 'Chandni Raat Mein', f: 'Dil Hi To Hai', y: 1963 },
  { t: 'Zindagi Har Kadam Ek Nayi Jung Hai', f: 'Meri Jung', y: 1985 },
  { t: 'Tera Saath Hai Kitna Pyara', f: 'Janbaaz', y: 1986 },
  { t: 'Har Kisi Ko Nahi Milta', f: 'Jaanbaaz', y: 1986 },
  { t: 'Jaane Kyun Log Pyar Karte Hain', f: 'Mr. India', y: 1987 },
  { t: 'Zindagi Ki Yahi Reet Hai', f: 'Mr. India', y: 1987 },
  { t: 'Ae Mere Humsafar', f: 'Qayamat Se Qayamat Tak', y: 1988 },
  { t: 'Gazab Ka Hai Din', f: 'Qayamat Se Qayamat Tak', y: 1988 },
  { t: 'Akele Hain To Kya Gham Hai', f: 'Qayamat Se Qayamat Tak', y: 1988 },
  { t: 'Tumse Milkar Na Jaane Kyun', f: 'Pyar Jhukta Nahin', y: 1985 },
  { t: 'Tere Mere Beech Mein', f: 'Ek Duuje Ke Liye', y: 1981 },
  { t: 'Hum Bane Tum Bane', f: 'Ek Duuje Ke Liye', y: 1981 },
  { t: 'Mere Jeevan Saathi', f: 'Ek Duuje Ke Liye', y: 1981 },
  { t: 'Solah Baras Ki Baali Umar', f: 'Ek Duuje Ke Liye', y: 1981 },
  { t: 'Kaise Bataye Kyun Tujhko Chaahe', f: 'Ishq Junoon', y: 2016 },
  { t: 'Tum Ko Dekha To Yeh Khayal Aaya', f: 'Saath Saath', y: 1982 },
  { t: 'Yeh Tera Ghar Yeh Mera Ghar', f: 'Saath Saath', y: 1982 },
  { t: 'Zindagi Jab Bhi Teri Bazm Mein', f: 'Umrao Jaan', y: 1981 },
  { t: 'In Aankhon Ki Masti Ke', f: 'Umrao Jaan', y: 1981 },
  { t: 'Dil Cheez Kya Hai', f: 'Umrao Jaan', y: 1981 },
  { t: 'Justuju Jiski Thi', f: 'Umrao Jaan', y: 1981 },
  { t: 'Ek Akela Is Sheher Mein', f: 'Gharaonda', y: 1977 },
  { t: 'Do Deewane Shehar Mein', f: 'Gharaonda', y: 1977 },
  { t: 'Aap Ki Aankhon Mein Kuch', f: 'Ghar', y: 1978 },
  { t: 'Phir Wohi Raat Hai', f: 'Ghar', y: 1978 },
  { t: 'Tere Bina Jiya Jaye Na', f: 'Ghar', y: 1978 },
  { t: 'Naam Gum Jayega', f: 'Kinara', y: 1977 },
  { t: 'Ek Hi Khwab', f: 'Kinara', y: 1977 },
  { t: 'Is Mod Se Jaate Hain', f: 'Aandhi', y: 1975 },
  { t: 'Tum Itna Jo Muskura Rahe Ho', f: 'Arth', y: 1982 },
  { t: 'Koi Yeh Kaise Bataye', f: 'Arth', y: 1982 },
  { t: 'Jhuki Jhuki Si Nazar', f: 'Arth', y: 1982 },
  { t: 'Hoshwalon Ko Khabar Kya', f: 'Sarfarosh', y: 1999 },
  { t: 'Zindagi Maut Na Ban Jaye', f: 'Sarfarosh', y: 1999 },
  { t: 'Sandese Aate Hain', f: 'Border', y: 1997 },
  { t: 'Ke Ghar Kab Aaoge', f: 'Border', y: 1997 },
  { t: 'Toote Hue Khwabon Ne', f: 'Madhumati', y: 1958 },
  { t: 'Jaane Kahan Gaye Woh Din', f: 'Mera Naam Joker', y: 1970 },
  { t: 'Jeena Yahan Marna Yahan', f: 'Mera Naam Joker', y: 1970 },
  { t: 'Kabhi Alvida Naa Kehna', f: 'Chalte Chalte', y: 1976 },
  { t: 'Dukki Pe Dukki Ho', f: 'Satte Pe Satta', y: 1982 },
  { t: 'Jeevan Se Bhari Teri Aankhen', f: 'Safar', y: 1970 },
  { t: 'Nadiya Se Dariya', f: 'Namkeen', y: 1982 },
  { t: 'Phoolon Ka Taron Ka', f: 'Hare Rama Hare Krishna', y: 1971 },
  { t: 'Dum Maro Dum', f: 'Hare Rama Hare Krishna', y: 1971 },
  { t: 'Musafir Hoon Main Bhi', f: 'Baaz', y: 1953 },
  { t: 'Aadmi Musafir Hai', f: 'Apnapan', y: 1977 },
  { t: 'Duniya Mein Logon Ko', f: 'Apna Desh', y: 1972 },
  { t: 'Mere Naina Sawan Bhadon', f: 'Mehbooba', y: 1976 },
  { t: 'Parde Mein Rehne Do', f: 'Shikar', y: 1968 },
  { t: 'Chal Ud Ja Re Panchhi', f: 'Bhabhi', y: 1957 },
  { t: 'Jab Koi Baat Bigad Jaye', f: 'Jurm', y: 1990 },
  { t: 'Tu Mile Dil Khile', f: 'Criminal', y: 1995 },
  { t: 'Bekarar Karke Hamein', f: 'Bees Saal Baad', y: 1962 },
  { t: 'Aap Ke Anurodh Pe', f: 'Anurodh', y: 1977 },
  { t: 'Jaane Kya Baat Hai', f: 'Sunny', y: 1984 },
  { t: 'Bheegi Bheegi Si Hai Raatein', f: 'Ajnabee', y: 1974 },
  { t: 'Woh Sham Kuch Ajeeb Thi', f: 'Khamoshi', y: 1969 },
  { t: 'Tum Pukar Lo', f: 'Khamoshi', y: 1969 },
  { t: 'Humein Aur Jeene Ki', f: 'Agar Tum Na Hote', y: 1983 },
  { t: 'Agar Tum Na Hote', f: 'Agar Tum Na Hote', y: 1983 },
];
