// Source of truth for the Gaana Wala library.
// Song entries are curated by hand; YouTube ids are resolved + verified by
// tools/resolve-youtube.mjs so nothing here needs a video id typed in.
//
// Fields per song: t = title, f = film, y = year, a = artist (non-film tracks),
// q = search-query override when the plain title is ambiguous.

export const stations = [
  {
    slug: 'saloon-wala',
    name: 'Saloon Wala',
    hi: 'सैलून वाला',
    tagline: 'The ₹30 haircut canon',
    blurb:
      'A ceiling fan, a cracked mirror, a steel bowl of lather and one speaker turned up past what it can handle. These are the songs that played while the barber asked you, again, whether you wanted it short on the sides.',
    art: 'saloon',
    accent: '#e0483a',
    accent2: '#f2b134',
    hours: [10, 11, 12, 13, 14, 15, 16, 17],
    songs: [
      { t: 'Tu Cheez Badi Hai Mast Mast', f: 'Mohra', y: 1994 },
      { t: 'Ole Ole', f: 'Yeh Dillagi', y: 1994 },
      { t: 'Yeh Kaali Kaali Aankhen', f: 'Baazigar', y: 1993 },
      { t: 'Sona Kitna Sona Hai', f: 'Hero No. 1', y: 1997 },
      { t: 'Churake Dil Mera', f: 'Main Khiladi Tu Anari', y: 1994, q: 'Chura Ke Dil Mera 4K video song Main Khiladi Tu Anari Akshay Shilpa' },
      { t: 'Akhiyon Se Goli Maare', f: 'Dulhe Raja', y: 1998, q: 'Akhiyon Se Goli Maare full video song Dulhe Raja Govinda Raveena' },
      { t: 'Ruk Ruk Ruk', f: 'Vijaypath', y: 1994 },
      { t: 'Jhanjhariya', f: 'Krishna', y: 1996 },
      { t: 'Dhak Dhak Karne Laga', f: 'Beta', y: 1992 },
      { t: 'Pehla Nasha', f: 'Jo Jeeta Wohi Sikandar', y: 1992 },
      { t: 'Kisi Disco Mein Jaaye', f: 'Bade Miyan Chote Miyan', y: 1998 },
      { t: 'Tumse Milne Ki Tamanna Hai', f: 'Saajan', y: 1991 },
    ],
  },
  {
    slug: 'truck-wala',
    name: 'Truck Wala',
    hi: 'ट्रक वाला',
    tagline: 'Horn OK Please, 2am',
    blurb:
      'The cabin canon. Sung at full volume on a dark stretch of national highway with nothing on either side, four hours still to go, and a photograph taped above the windscreen. Mostly about distance, letters, and people who did not wait.',
    art: 'truck',
    accent: '#f2b134',
    accent2: '#2d7d8a',
    hours: [22, 23, 0, 1, 2, 3, 4],
    songs: [
      { t: 'Chitthi Aayi Hai', f: 'Naam', y: 1986 },
      { t: 'Main Nikla Gaddi Leke', f: 'Gadar: Ek Prem Katha', y: 2001, q: 'Main Nikla Gaddi Leke Gadar 2001 Udit Narayan Sunny Deol full song' },
      { t: 'Pardesi Pardesi Jaana Nahin', f: 'Raja Hindustani', y: 1996 },
      { t: 'Tujhe Dekha To Ye Jaana Sanam', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
      { t: 'Chalte Chalte Mere Yeh Geet', f: 'Chalte Chalte', y: 1976 },
      { t: 'Ae Kaash Ke Hum', f: 'Kabhi Haan Kabhi Naa', y: 1994 },
      { t: 'Kya Hua Tera Wada', f: 'Hum Kisise Kum Naheen', y: 1977 },
      { t: 'Sochenge Tumhe Pyar', f: 'Deewana', y: 1992 },
      { t: 'Tadap Tadap Ke', f: 'Hum Dil De Chuke Sanam', y: 1999 },
      { t: 'Meri Mehbooba', f: 'Pardes', y: 1997 },
      { t: 'Dil Hoom Hoom Kare', f: 'Rudaali', y: 1993, q: 'Dil Hoom Hoom Kare Rudaali Lata Mangeshkar Bhupen Hazarika' },
      { t: 'Lambi Judai', f: 'Hero', y: 1983 },
    ],
  },
  {
    slug: 'bus-wala',
    name: 'Bus Wala',
    hi: 'बस वाला',
    tagline: 'Window seat, morning ghat',
    blurb:
      'State transport, 7am, the window jammed half open. Somebody up front has a phone speaker going and nobody minds. Songs for hills on one side, a valley on the other, and a conductor who knows every stop by heart.',
    art: 'bus',
    accent: '#2d7d8a',
    accent2: '#f2b134',
    hours: [6, 7, 8, 9],
    songs: [
      { t: 'Zindagi Ek Safar Hai Suhana', f: 'Andaz', y: 1971 },
      { t: 'Musafir Hoon Yaaron', f: 'Parichay', y: 1972 },
      { t: 'Suhana Safar Aur Yeh Mausam Haseen', f: 'Madhumati', y: 1958 },
      { t: 'Yeh Dosti Hum Nahi Todenge', f: 'Sholay', y: 1975 },
      { t: 'Panchhi Banoon Udti Phiroon', f: 'Chori Chori', y: 1956 },
      { t: 'Safarnama', f: 'Tamasha', y: 2015 },
      { t: 'Yun Hi Chala Chal', f: 'Swades', y: 2004 },
      { t: 'Aane Wala Pal', f: 'Golmaal', y: 1979 },
      { t: 'Ruk Jana Nahin', f: 'Imtihan', y: 1974 },
      { t: 'Mera Joota Hai Japani', f: 'Shree 420', y: 1955 },
      { t: 'Chala Jaata Hoon', f: 'Mere Jeevan Saathi', y: 1972 },
      { t: 'Dil Chahta Hai', f: 'Dil Chahta Hai', y: 2001 },
    ],
  },
  {
    slug: 'auto-wala',
    name: 'Auto Wala',
    hi: 'ऑटो वाला',
    tagline: 'Speaker bigger than the meter',
    blurb:
      'Three wheels, mirror-work upholstery, a subwoofer where the toolbox should be. He takes the corner at an angle the physics does not allow and the bass does not drop for the whole ride.',
    art: 'auto',
    accent: '#f0c419',
    accent2: '#1c8a4a',
    hours: [18, 19, 20, 21],
    songs: [
      { t: 'Dilbar Dilbar', f: 'Sirf Tum', y: 1999 },
      { t: 'Kaanta Laga', a: 'DJ Doll', y: 2002 },
      { t: 'Tunak Tunak Tun', a: 'Daler Mehndi', y: 1998 },
      { t: 'Bolo Ta Ra Ra', a: 'Daler Mehndi', y: 1995 },
      { t: 'Aankh Marey', f: 'Simmba', y: 2018 },
      { t: 'Munni Badnaam Hui', f: 'Dabangg', y: 2010 },
      { t: 'Sheila Ki Jawani', f: 'Tees Maar Khan', y: 2010 },
      { t: 'Chikni Chameli', f: 'Agneepath', y: 2012 },
      { t: 'Lungi Dance', f: 'Chennai Express', y: 2013 },
      { t: 'Abhi Toh Party Shuru Hui Hai', f: 'Khoobsurat', y: 2014 },
      { t: 'Tamma Tamma Loge', f: 'Thanedaar', y: 1990 },
      { t: 'Saturday Saturday', f: 'Humpty Sharma Ki Dulhania', y: 2014 },
    ],
  },
  {
    slug: 'chai-tapri',
    name: 'Chai Tapri',
    hi: 'चाय टपरी',
    tagline: 'Golden hour, cutting chai',
    blurb:
      'Steel glasses, plastic stools, one kettle that has never been washed and gossip that solves nothing and everything. The sun is going down behind the flyover and nobody has anywhere to be for twenty more minutes.',
    art: 'chai',
    accent: '#c96f2c',
    accent2: '#e8a33d',
    hours: [16, 17, 18],
    songs: [
      { t: 'Kabira', f: 'Yeh Jawaani Hai Deewani', y: 2013 },
      { t: 'Ilahi', f: 'Yeh Jawaani Hai Deewani', y: 2013, q: 'Ilahi full video song Yeh Jawaani Hai Deewani Arijit Singh Ranbir' },
      { t: 'Phir Le Aaya Dil', f: 'Barfi!', y: 2012 },
      { t: 'Iktara', f: 'Wake Up Sid', y: 2009 },
      { t: 'Behti Hawa Sa Tha Woh', f: '3 Idiots', y: 2009 },
      { t: 'Khoya Khoya Chand', f: 'Kala Bazar', y: 1960 },
      { t: 'Tum Ho Toh', f: 'Rock On!!', y: 2008 },
      { t: 'Masakali', f: 'Delhi-6', y: 2009 },
      { t: 'Nadaan Parindey', f: 'Rockstar', y: 2011 },
      { t: 'Bandeh', f: 'Black Friday', y: 2004, a: 'Indian Ocean' },
      { t: 'Ma Rewa', a: 'Indian Ocean' },
      { t: 'Ek Garam Chai Ki Pyali Ho', q: 'Ek Garam Chai Ki Pyali Ho Kishore Kumar old hindi song' },
    ],
  },
  {
    slug: 'gym-wala',
    name: 'Gym Wala',
    hi: 'जिम वाला',
    tagline: 'Last set, no spotter',
    blurb:
      'Basement gym, one mirror wall, rusted plates and a trainer named Pehelwan ji. The playlist has exactly one job and it does it without subtlety.',
    art: 'gym',
    accent: '#d63b2f',
    accent2: '#222831',
    hours: [5, 6, 7, 19, 20],
    songs: [
      { t: 'Sultan Title Track', f: 'Sultan', y: 2016 },
      { t: 'Brothers Anthem', f: 'Brothers', y: 2015 },
      { t: 'Zinda', f: 'Bhaag Milkha Bhaag', y: 2013 },
      { t: 'Ziddi Dil', f: 'Mary Kom', y: 2014 },
      { t: 'Malang', f: 'Dhoom 3', y: 2013 },
      { t: 'Khalibali', f: 'Padmaavat', y: 2018 },
      { t: 'Sher Aaya Sher', f: 'Gully Boy', y: 2019 },
      { t: 'Apna Time Aayega', f: 'Gully Boy', y: 2019 },
      { t: 'Dangal Title Track', f: 'Dangal', y: 2016 },
      { t: 'Get Ready To Fight', f: 'Baaghi', y: 2016 },
      { t: 'Bhaag DK Bose', f: 'Delhi Belly', y: 2011 },
      { t: 'Chak Lein De', f: 'Chandni Chowk To China', y: 2009 },
    ],
  },
  {
    slug: 'shaadi-wala',
    name: 'Shaadi Wala',
    hi: 'शादी वाला',
    tagline: 'Baraat is not moving',
    blurb:
      'Generator lights, a dhol that started at four in the afternoon, and every uncle convinced the floor is his. The baraat has covered forty metres in an hour and a half. Nobody is complaining.',
    art: 'shaadi',
    accent: '#e0206c',
    accent2: '#f2b134',
    hours: [19, 20, 21, 22],
    songs: [
      { t: 'Didi Tera Devar Deewana', f: 'Hum Aapke Hain Koun..!', y: 1994 },
      { t: 'Mehndi Laga Ke Rakhna', f: 'Dilwale Dulhania Le Jayenge', y: 1995 },
      { t: 'Bole Chudiyan', f: 'Kabhi Khushi Kabhie Gham', y: 2001 },
      { t: 'Aaj Mere Yaar Ki Shaadi Hai', f: 'Aadmi Sadak Ka', y: 1977 },
      { t: 'London Thumakda', f: 'Queen', y: 2014 },
      { t: 'Nagada Sang Dhol', f: 'Goliyon Ki Raasleela Ram-Leela', y: 2013 },
      { t: 'Gallan Goodiyaan', f: 'Dil Dhadakne Do', y: 2015 },
      { t: 'Saajanji Ghar Aaye', f: 'Kuch Kuch Hota Hai', y: 1998 },
      { t: 'Dulhe Ka Sehra', f: 'Dhadkan', y: 2000 },
      { t: 'Chunari Chunari', f: 'Biwi No.1', y: 1999 },
      { t: 'Kajra Re', f: 'Bunty Aur Babli', y: 2005 },
      { t: 'Wah Wah Ramji', f: 'Hum Aapke Hain Koun..!', y: 1994 },
    ],
  },
  {
    slug: 'dhaba-wala',
    name: 'Dhaba Wala',
    hi: 'ढाबा वाला',
    tagline: 'Charpai, dal makhani, 1am',
    blurb:
      'Somewhere on GT Road. String lights, a tandoor still going, charpais laid out in the gravel. Punjabi at a volume that carries to the next dhaba, which is playing the same song.',
    art: 'dhaba',
    accent: '#e07b39',
    accent2: '#1c8a4a',
    hours: [21, 22, 23, 0, 1],
    songs: [
      { t: 'Mundian To Bach Ke', a: 'Panjabi MC', y: 1998 },
      { t: 'Gur Naal Ishq Mitha', a: 'Malkit Singh', q: 'Gur Nalo Ishq Mitha Malkit Singh original bhangra song' },
      { t: 'Jugni', f: 'Cocktail', y: 2012 },
      { t: 'Sadi Gali', f: 'Tanu Weds Manu', y: 2011 },
      { t: 'Kala Chashma', f: 'Baar Baar Dekho', y: 2016 },
      { t: 'Patiala Peg', a: 'Diljit Dosanjh', y: 2015 },
      { t: 'Laembadgini', a: 'Diljit Dosanjh', y: 2016 },
      { t: 'Do You Know', a: 'Diljit Dosanjh', y: 2011, q: 'Do You Know Diljit Dosanjh full punjabi song album' },
      { t: 'High Rated Gabru', a: 'Guru Randhawa', y: 2017 },
      { t: 'Lamberghini', a: 'The Doorbeen', y: 2018 },
      { t: 'Brown Munde', a: 'AP Dhillon', y: 2020 },
      { t: 'Yaar Anmulle', a: 'Sharry Mann', y: 2011 },
    ],
  },
  {
    slug: 'paan-wala',
    name: 'Paan Wala',
    hi: 'पान वाला',
    tagline: 'Meetha, extra gulkand',
    blurb:
      'A glass case of silver leaf and supari, a transistor on the shelf, and a queue of three men who came for cigarettes and stayed for the argument. Pure eighties masala, no apologies.',
    art: 'paan',
    accent: '#1c8a4a',
    accent2: '#e0483a',
    hours: [20, 21, 22],
    songs: [
      { t: 'Khaike Paan Banaraswala', f: 'Don', y: 1978 },
      { t: 'I Am A Disco Dancer', f: 'Disco Dancer', y: 1982 },
      { t: 'Jimmy Jimmy Aaja', f: 'Disco Dancer', y: 1982 },
      { t: 'Ui Amma Ui Amma', f: 'Mawaali', y: 1983 },
      { t: 'Aap Jaisa Koi', f: 'Qurbani', y: 1980 },
      { t: 'Jawani Janeman', f: 'Namak Halaal', y: 1982 },
      { t: 'Pag Ghungroo Baandh', f: 'Namak Halaal', y: 1982 },
      { t: 'Ek Do Teen', f: 'Tezaab', y: 1988 },
      { t: 'Papa Kehte Hain', f: 'Qayamat Se Qayamat Tak', y: 1988 },
      { t: 'Tirchi Topiwale', f: 'Tridev', y: 1989 },
      { t: 'Oye Oye', f: 'Tridev', y: 1989 },
      { t: 'Yaad Aa Raha Hai', f: 'Disco Dancer', y: 1982 },
    ],
  },
  {
    slug: 'mandir-wala',
    name: 'Mandir Wala',
    hi: 'मंदिर वाला',
    tagline: '5am, bell and loudspeaker',
    blurb:
      'Before the traffic starts. A bell, a conch, agarbatti smoke and a horn speaker on a pole that the whole colony can hear whether it wants to or not.',
    art: 'mandir',
    accent: '#e8931f',
    accent2: '#c0392b',
    hours: [4, 5, 6, 7],
    songs: [
      { t: 'Om Jai Jagdish Hare', q: 'Om Jai Jagdish Hare aarti' },
      { t: 'Achyutam Keshavam', a: 'Bhajan' },
      { t: 'Hanuman Chalisa', a: 'Hariharan', q: 'Shree Hanuman Chalisa Hariharan Gulshan Kumar' },
      { t: 'Gayatri Mantra', a: 'Anuradha Paudwal' },
      { t: 'Aisi Lagi Lagan', a: 'Anup Jalota' },
      { t: 'Jai Ganesh Deva', q: 'Jai Ganesh Deva aarti' },
      { t: 'Sukhkarta Dukhharta', q: 'Sukhkarta Dukhharta Ganpati aarti' },
      { t: 'Raghupati Raghav Raja Ram', q: 'Raghupati Raghav Raja Ram bhajan' },
      { t: 'Vaishnav Jan To', q: 'Vaishnav Jan To Tene Kahiye bhajan' },
      { t: 'Man Tarpat Hari Darshan Ko Aaj', f: 'Baiju Bawra', y: 1952, q: 'Man Tarpat Hari Darshan Ko Aaj Mohammed Rafi Baiju Bawra' },
      { t: 'Allah Tero Naam', f: 'Hum Dono', y: 1961, q: 'Allah Tero Naam Ishwar Tero Naam Lata Mangeshkar Hum Dono original' },
      { t: 'Tu Pyar Ka Sagar Hai', f: 'Seema', y: 1955 },
    ],
  },
  {
    slug: 'qawwali-wala',
    name: 'Qawwali Wala',
    hi: 'कव्वाली वाला',
    tagline: 'Dargah courtyard, after Isha',
    blurb:
      'Harmonium, tabla, and eight men clapping on the off-beat until the courtyard gives in. It starts slow. It does not stay slow.',
    art: 'qawwali',
    accent: '#2f6f6b',
    accent2: '#d9a441',
    hours: [21, 22, 23, 0],
    songs: [
      { t: 'Dama Dam Mast Qalandar', a: 'Nusrat Fateh Ali Khan', q: 'Dam Mast Qalandar Mast Mast Nusrat Fateh Ali Khan qawwali' },
      { t: 'Tumhe Dillagi', a: 'Nusrat Fateh Ali Khan', q: 'Tumhe Dillagi Bhool Jani Padegi Nusrat Fateh Ali Khan original qawwali' },
      { t: 'Afreen Afreen', a: 'Nusrat Fateh Ali Khan' },
      { t: 'Sanson Ki Mala Pe', a: 'Nusrat Fateh Ali Khan' },
      { t: 'Bhar Do Jholi Meri', f: 'Bajrangi Bhaijaan', y: 2015 },
      { t: 'Kun Faya Kun', f: 'Rockstar', y: 2011 },
      { t: 'Khwaja Mere Khwaja', f: 'Jodhaa Akbar', y: 2008 },
      { t: 'Piya Haji Ali', f: 'Fiza', y: 2000, q: 'Piya Haji Ali full song Fiza A R Rahman Srinivas' },
      { t: 'Arziyan', f: 'Delhi-6', y: 2009 },
      { t: 'Parda Hai Parda', f: 'Amar Akbar Anthony', y: 1977 },
      { t: 'Hai Agar Dushman', f: 'Hum Kisise Kum Naheen', y: 1977 },
      { t: 'Tajdar-e-Haram', a: 'Atif Aslam', q: 'Tajdar-e-Haram Atif Aslam Coke Studio Season 8 Episode 1' },
    ],
  },
  {
    slug: 'train-wala',
    name: 'Train Wala',
    hi: 'ट्रेन वाला',
    tagline: 'Side upper, 3am, chai',
    blurb:
      'Sleeper class with the window shutter up. Fields going past in the dark, somebody snoring two berths down, and a chaiwala who will come through at exactly the wrong hour. Kishore, mostly.',
    art: 'train',
    accent: '#3b5a7a',
    accent2: '#e8a33d',
    hours: [23, 0, 1, 2, 3, 4, 5],
    songs: [
      { t: 'Chaiyya Chaiyya', f: 'Dil Se..', y: 1998 },
      { t: 'Mere Sapno Ki Rani', f: 'Aradhana', y: 1969, q: 'Mere Sapno Ki Rani Aradhana Kishore Kumar Rajesh Khanna original song' },
      { t: 'Gaadi Bula Rahi Hai', f: 'Dost', y: 1974 },
      { t: 'Zindagi Ka Safar', f: 'Safar', y: 1970 },
      { t: 'Kuch To Log Kahenge', f: 'Amar Prem', y: 1972 },
      { t: 'Chingari Koi Bhadke', f: 'Amar Prem', y: 1972 },
      { t: 'Yeh Shaam Mastani', f: 'Kati Patang', y: 1970 },
      { t: 'Diye Jalte Hain', f: 'Namak Haraam', y: 1973 },
      { t: 'Main Shayar Badnaam', f: 'Namak Haraam', y: 1973 },
      { t: 'O Mere Dil Ke Chain', f: 'Mere Jeevan Saathi', y: 1972 },
      { t: 'Raat Kali Ek Khwab Mein Aayi', f: 'Buddha Mil Gaya', y: 1971 },
      { t: 'Rail Gaadi', a: 'Ashok Kumar', q: 'Rail Gaadi Ashok Kumar song' },
    ],
  },
  {
    slug: 'barish-wala',
    name: 'Barish Wala',
    hi: 'बारिश वाला',
    tagline: 'First rain, grille open',
    blurb:
      'The smell before it lands, then the sound on the tin awning. Power will go in about four minutes. Somebody is already making pakodas.',
    art: 'barish',
    accent: '#4a7fa5',
    accent2: '#7fb069',
    hours: [15, 16, 17, 18, 19],
    songs: [
      { t: 'Rimjhim Gire Sawan', f: 'Manzil', y: 1979 },
      { t: 'Bheegi Bheegi Raaton Mein', f: 'Ajnabee', y: 1974, q: 'Bheegi Bheegi Raaton Mein Ajnabee Kishore Kumar Lata Mangeshkar 1974' },
      { t: 'Ab Ke Sawan', a: 'Shubha Mudgal', y: 1999 },
      { t: 'Barso Re', f: 'Guru', y: 2007 },
      { t: 'Tip Tip Barsa Paani', f: 'Mohra', y: 1994 },
      { t: 'Kaate Nahi Kat Te', f: 'Mr. India', y: 1987 },
      { t: 'Ghanan Ghanan', f: 'Lagaan', y: 2001 },
      { t: 'Koi Ladki Hai', f: 'Dil To Pagal Hai', y: 1997 },
      { t: 'Bheegi Bheegi', f: 'Gangster', y: 2006, q: 'Bheegi Bheegi Gangster James Atif Aslam full song Emraan Kangana' },
      { t: 'Zara Zara', f: 'Rehnaa Hai Terre Dil Mein', y: 2001 },
      { t: 'Megha Re Megha', f: 'Pyaasa Sawan', y: 1981 },
      { t: 'Lagi Aaj Sawan Ki', f: 'Chandni', y: 1989 },
    ],
  },
  {
    slug: 'padhai-wala',
    name: 'Padhai Wala',
    hi: 'पढ़ाई वाला',
    tagline: 'Table lamp, 2am, exam in six days',
    blurb:
      'One lamp, one desk, a cold cup of Bournvita and a syllabus that is not going to finish itself. Soft enough to keep going, sad enough to feel like it matters.',
    art: 'padhai',
    accent: '#6b5b95',
    accent2: '#e8a33d',
    hours: [22, 23, 0, 1, 2],
    songs: [
      { t: 'Tum Ho', f: 'Rockstar', y: 2011 },
      { t: 'Agar Tum Saath Ho', f: 'Tamasha', y: 2015 },
      { t: 'Khamoshiyan', f: 'Khamoshiyan', y: 2015 },
      { t: 'Tere Bina', f: 'Guru', y: 2007 },
      { t: 'Luka Chuppi', f: 'Rang De Basanti', y: 2006 },
      { t: 'Ae Ajnabi', f: 'Dil Se..', y: 1998 },
      { t: 'Naina Da Kya Kasoor', f: 'Andhadhun', y: 2018 },
      { t: 'Raabta', f: 'Agent Vinod', y: 2012 },
      { t: 'Hasi', f: 'Hamari Adhuri Kahani', y: 2015 },
      { t: 'Jag Ghoomeya', f: 'Sultan', y: 2016, q: 'Jag Ghoomeya Sultan Rahat Fateh Ali Khan full song Salman Anushka' },
      { t: 'Manja', f: 'Kai Po Che!', y: 2013 },
      { t: 'Kho Gaye Hum Kahan', f: 'Baar Baar Dekho', y: 2016 },
    ],
  },
];

export function searchQuery(song) {
  if (song.q) return song.q;
  const parts = [song.t];
  if (song.f) parts.push(song.f);
  else if (song.a) parts.push(song.a);
  parts.push('song');
  return parts.join(' ');
}
